// ════════════════════════════════════════════════════
// kelimeler.js  –  Veri & stats başlatma  v5
//                  user-scoped + guest merge
//                  YDT Master Pack (1300+ kelime, 5 seviye)
// ════════════════════════════════════════════════════

function getUserKey(key) {
    const uid = window._currentUser?.uid || 'guest';
    return `ydt_${uid}_${key}`;
}

// Global olarak tanımla — module script'ten window.allData ile erişilir
window.allData = window.allData || {};
window.stats   = window.stats   || {};
var allData = window.allData;
var stats   = window.stats;

// Kelime nesnesi üretici — tekrar yazmayı önler
function _w(eng, tr, pos, mnemonic) {
    return { eng, tr, pos, mnemonic: mnemonic || '', story: '', errorCount: 0, correctStreak: 0, sm2_ef: 2.5, sm2_interval: 0, sm2_next: null };
}

// ════════════════════════════════════════════════════
// YDT MASTER PACK — 1307 kelime, 5 seviye
// ════════════════════════════════════════════════════
const YDT_STARTER_PACK = {

"🟢 A2 Temel": [
    _w("ability","yetenek / beceri","n","A harfi gibi açık — yeteneğin kapısı"),
    _w("achieve","başarmak / elde etmek","v","A+chieve: çaba ile hedefe ulaş"),
    _w("affect","etkilemek","v","Bir şeyi affect etmek = onun üzerinde iz bırakmak"),
    _w("allow","izin vermek","v","Alow = 'izin ver' — ALL = herkes için"),
    _w("amount","miktar / tutar","n","A mount (dağ) kadar çok = büyük miktar"),
    _w("ancient","antik / çok eski","adj","Anc = ancestor (ata) — eski şeyler"),
    _w("anxious","endişeli / kaygılı","adj","Anxiety'nin kökü — endişe dolu"),
    _w("approach","yaklaşmak / yaklaşım","v","A+pro+ach: hedefe doğru profesyonelce yaklaş"),
    _w("area","alan / bölge","n","Arena'nın kısaltması — açık alan"),
    _w("argue","tartışmak","v","Arg = kızgın ses — tartışma sesi"),
    _w("avoid","kaçınmak","v","A+void = boşluk bırak — uzak dur"),
    _w("aware","farkında","adj","A+ware: gözlerini aç, dikkatli ol"),
    _w("basic","temel / basit","adj","Base (taban) + ic — temelden gelen"),
    _w("benefit","fayda / yarar","n","Bene (iyi) + fit = iyiliğe uyan"),
    _w("besides","bunun yanı sıra","prep","Be+sides: iki tarafta da var"),
    _w("boring","sıkıcı","adj","Bore = delmek — sıkıntı zihnini deler"),
    _w("brave","cesur / yiğit","adj","B+rave = rave party'e gidecek kadar cesur"),
    _w("bright","parlak / zeki","adj","Brightness — parlaklık, zeka ışığı"),
    _w("bring","getirmek","v","Bring it: onu buraya getir"),
    _w("build","inşa etmek","v","Builder — inşaatçı, bir şey yapar"),
    _w("busy","meşgul","adj","Bee (arı) busy = arı gibi çalışkan"),
    _w("calm","sakin / rahat","adj","Balm (merhem) gibi sakinleştiren"),
    _w("care","önem vermek / ilgilenmek","v","Careful — dikkatli, önem veren"),
    _w("cause","neden / sebep olmak","n","Cause and effect — sebep-sonuç"),
    _w("change","değişmek / değiştirmek","v","Exchange — karşılıklı değişim"),
    _w("cheap","ucuz","adj","Ch+eap: kolay erişilen"),
    _w("choose","seçmek","v","Choice — seçim yaparken 'choose'"),
    _w("citizen","vatandaş","n","City+zen — şehrin sahibi"),
    _w("clear","açık / net","adj","Crystal clear — kristal gibi net"),
    _w("close","yakın / kapatmak","adj","Closet — yakın mesafedeki dolap"),
    _w("collect","toplamak","v","Collection — koleksiyon, bir araya getirme"),
    _w("comfortable","rahat","adj","Comfort+able: rahatlık yeteneği"),
    _w("common","yaygın / ortak","adj","Common ground — ortak zemin"),
    _w("compare","karşılaştırmak","v","Com+pare: eşit parça — kıyasla"),
    _w("complete","tamamlamak","adj","100% = complete — tam"),
    _w("connect","bağlamak","v","Connection — bağlantı"),
    _w("continue","devam etmek","v","Continuous — kesintisiz devam"),
    _w("correct","doğru / düzeltmek","adj","Correct answer — doğru cevap"),
    _w("cost","maliyet / mal olmak","n","Cost of living — yaşam maliyeti"),
    _w("create","yaratmak / oluşturmak","v","Creative — yaratıcı"),
    _w("crowd","kalabalık","n","Crowded — kalabalık yer"),
    _w("culture","kültür","n","Agricultural — tarım kültürü"),
    _w("danger","tehlike","n","Dangerous — tehlikeli"),
    _w("dark","karanlık","adj","Darkness — karanlık"),
    _w("decide","karar vermek","v","Decision — karar"),
    _w("describe","tanımlamak","v","Description — tanım, açıklama"),
    _w("develop","geliştirmek","v","Development — gelişim"),
    _w("different","farklı","adj","Difference — fark"),
    _w("difficult","zor","adj","Difficulty — zorluk"),
    _w("discover","keşfetmek","v","Discovery — keşif"),
    _w("discuss","tartışmak / konuşmak","v","Discussion — tartışma"),
    _w("distance","mesafe","n","Distant — uzakta"),
    _w("divide","bölmek / ayırmak","v","Division — bölme"),
    _w("doubt","şüphe etmek","v","Without a doubt — şüphesiz"),
    _w("dream","rüya / hayal","n","Dreamer — hayalci"),
    _w("during","süresince / boyunca","prep","Duration — süre"),
    _w("earn","kazanmak","v","Earnings — kazanç"),
    _w("educate","eğitmek","v","Education — eğitim"),
    _w("effort","çaba / gayret","n","Make an effort — çaba göster"),
    _w("empty","boş","adj","Empty vessel — boş kap"),
    _w("enjoy","zevk almak","v","Enjoyable — zevkli"),
    _w("enough","yeterli","adj","Enough is enough — yeter"),
    _w("enter","girmek","v","Entrance — giriş"),
    _w("equal","eşit","adj","Equality — eşitlik"),
    _w("escape","kaçmak","v","Fire escape — yangın kaçışı"),
    _w("even","bile / düz","adv","Even numbers — çift sayılar"),
    _w("event","olay / etkinlik","n","Eventual — sonunda olan"),
    _w("example","örnek","n","For example — örneğin"),
    _w("excited","heyecanlı","adj","Excitement — heyecan"),
    _w("expect","beklemek","v","Expectation — beklenti"),
    _w("experience","deneyim","n","Experienced — deneyimli"),
    _w("explain","açıklamak","v","Explanation — açıklama"),
    _w("fail","başarısız olmak","v","Failure — başarısızlık"),
    _w("fair","adil / fuar","adj","Fairness — adalet"),
    _w("fall","düşmek / sonbahar","v","Rainfall — yağmur yağışı"),
    _w("familiar","tanıdık","adj","Family — aile gibi tanıdık"),
    _w("famous","ünlü","adj","Fame — şöhret"),
    _w("far","uzak","adj","Faraway — çok uzak"),
    _w("feel","hissetmek","v","Feelings — duygular"),
    _w("fill","doldurmak","v","Fulfill — yerine getirmek"),
    _w("find","bulmak","v","Finding — bulgu"),
    _w("focus","odaklanmak","v","Focus on — üzerine odaklan"),
    _w("follow","takip etmek","v","Follower — takipçi"),
    _w("force","güç / zorlamak","n","Forceful — güçlü"),
    _w("forget","unutmak","v","Forgetful — unutkan"),
    _w("friendly","arkadaş canlısı","adj","Friend+ly — arkadaşça"),
    _w("from","dan / den","prep","From here — buradan"),
    _w("fun","eğlence","n","Funny — komik, eğlenceli"),
    _w("future","gelecek","n","Future plans — gelecek planları"),
    _w("general","genel","adj","Generally — genel olarak"),
    _w("give","vermek","v","Give and take — ver ve al"),
    _w("goal","hedef / gol","n","Goal setting — hedef belirleme"),
    _w("group","grup","n","Group work — grup çalışması"),
    _w("grow","büyümek","v","Growth — büyüme"),
    _w("guess","tahmin etmek","v","Best guess — en iyi tahmin"),
    _w("habit","alışkanlık","n","Habitual — alışılmış"),
    _w("happen","olmak / gerçekleşmek","v","What happened? — ne oldu?"),
    _w("hard","zor / sert","adj","Hardship — zorluk"),
    _w("harm","zarar vermek","v","Harmful — zararlı"),
    _w("health","sağlık","n","Healthy — sağlıklı"),
    _w("help","yardım etmek","v","Helpful — yardımsever"),
    _w("honest","dürüst","adj","Honesty — dürüstlük"),
    _w("hope","umut etmek","v","Hopeful — umutlu"),
    _w("huge","kocaman / çok büyük","adj","Huge difference — büyük fark"),
    _w("imagine","hayal etmek","v","Imagination — hayal gücü"),
    _w("improve","geliştirmek","v","Improvement — gelişme"),
    _w("include","dahil etmek","v","Inclusive — kapsayıcı"),
    _w("increase","artmak / artırmak","v","Increase in price — fiyat artışı"),
    _w("instead","yerine / bunun yerine","adv","Instead of — yerine"),
    _w("interest","ilgi / faiz","n","Interesting — ilginç"),
    _w("invite","davet etmek","v","Invitation — davet"),
    _w("join","katılmak","v","Join the group — gruba katıl"),
    _w("journey","yolculuk","n","Life journey — hayat yolculuğu"),
    _w("judge","yargılamak / hakim","v","Judgment — yargılama"),
    _w("keep","tutmak / devam ettirmek","v","Keep going — devam et"),
    _w("kind","nazik / tür","adj","Kindness — nezaket"),
    _w("knowledge","bilgi","n","Knowledge is power — bilgi güçtür"),
    _w("laugh","gülmek","v","Laughter — kahkaha"),
    _w("lead","önderlik etmek","v","Leader — lider"),
    _w("learn","öğrenmek","v","Learner — öğrenci"),
    _w("leave","ayrılmak / bırakmak","v","Leave behind — geride bırak"),
    _w("listen","dinlemek","v","Listener — dinleyici"),
    _w("local","yerel","adj","Local news — yerel haber"),
    _w("lonely","yalnız","adj","Loneliness — yalnızlık"),
    _w("manage","yönetmek / başarabilmek","v","Manager — yönetici"),
    _w("mean","anlamına gelmek / kaba","v","Meaning — anlam"),
    _w("meet","buluşmak","v","Meeting — toplantı"),
    _w("memory","hafıza / anı","n","Memorable — unutulmaz"),
    _w("message","mesaj","n","Messenger — mesaj gönderen"),
    _w("mind","akıl / umursamak","n","Mindful — dikkatli"),
    _w("miss","özlemek / kaçırmak","v","Missing — eksik, özlenen"),
    _w("move","hareket etmek","v","Movement — hareket"),
    _w("natural","doğal","adj","Nature — doğa"),
    _w("nervous","sinirli / gergin","adj","Nervousness — gerginlik"),
    _w("notice","fark etmek","v","Noticeable — göze çarpan"),
    _w("offer","teklif etmek","v","Offering — teklif"),
    _w("often","sık sık","adv","More often — daha sık"),
    _w("opinion","görüş / fikir","n","In my opinion — bence"),
    _w("opportunity","fırsat","n","Opportunity knocks — fırsat kapıya gelir"),
    _w("organize","düzenlemek","v","Organization — organizasyon"),
    _w("own","sahip olmak / kendi","v","Owner — sahip"),
    _w("patient","sabırlı / hasta","adj","Patience — sabır"),
    _w("perfect","mükemmel","adj","Perfection — mükemmellik"),
    _w("plan","plan yapmak","v","Planning — planlama"),
    _w("polite","nazik / kibar","adj","Politeness — kibarlık"),
    _w("popular","popüler / sevilen","adj","Popularity — popülerlik"),
    _w("possible","mümkün","adj","Possibility — olasılık"),
    _w("prepare","hazırlanmak","v","Preparation — hazırlık"),
    _w("prevent","önlemek","v","Prevention — önleme"),
    _w("problem","sorun / problem","n","Problematic — sorunlu"),
    _w("produce","üretmek","v","Product — ürün"),
    _w("protect","korumak","v","Protection — koruma"),
    _w("provide","sağlamak / vermek","v","Provider — sağlayıcı"),
    _w("public","halka açık / kamu","adj","Publicly — halka açık olarak"),
    _w("purpose","amaç / niyet","n","On purpose — kasıtlı olarak"),
    _w("quality","kalite","n","High quality — yüksek kalite"),
    _w("question","soru / sorgulamak","n","Questionable — sorgulanabilir"),
    _w("quick","hızlı","adj","Quickly — hızlıca"),
    _w("quiet","sessiz","adj","Quietness — sessizlik"),
    _w("raise","yükseltmek","v","Raise a question — soru sor"),
    _w("reach","ulaşmak","v","Reachable — ulaşılabilir"),
    _w("ready","hazır","adj","Get ready — hazırlan"),
    _w("reason","sebep / neden","n","Reasonable — makul"),
    _w("receive","almak","v","Receipt — makbuz"),
    _w("reduce","azaltmak","v","Reduction — azalma"),
    _w("remember","hatırlamak","v","Memorable — hatırlanabilir"),
    _w("repair","tamir etmek","v","Repairman — tamirci"),
    _w("respect","saygı göstermek","v","Respectful — saygılı"),
    _w("result","sonuç","n","As a result — sonuç olarak"),
    _w("return","geri dönmek","v","Return ticket — gidiş-dönüş bilet"),
    _w("rich","zengin","adj","Richness — zenginlik"),
    _w("right","doğru / hak","adj","Right answer — doğru cevap"),
    _w("risk","risk / tehlike","n","Risky — riskli"),
    _w("role","rol / görev","n","Role model — rol model"),
    _w("rule","kural","n","Ruler — cetvel / yönetici"),
    _w("safe","güvenli","adj","Safety — güvenlik"),
    _w("save","kurtarmak / tasarruf etmek","v","Savings — tasarruf"),
    _w("scared","korkmuş","adj","Scary — ürkütücü"),
    _w("seem","görünmek / gibi görünmek","v","Seemingly — görünüşe göre"),
    _w("serious","ciddi","adj","Seriously — ciddiye alarak"),
    _w("share","paylaşmak","v","Sharing is caring — paylaşmak önemsemektir"),
    _w("simple","basit / sade","adj","Simplicity — sadelik"),
    _w("skill","beceri","n","Skilled — yetenekli"),
    _w("slow","yavaş","adj","Slowly — yavaşça"),
    _w("smart","zeki / akıllı","adj","Smartness — zeka"),
    _w("social","sosyal / toplumsal","adj","Society — toplum"),
    _w("solve","çözmek","v","Solution — çözüm"),
    _w("sometimes","bazen","adv","Sometimes I forget — bazen unuturum"),
    _w("special","özel","adj","Specialty — uzmanlık"),
    _w("spend","harcamak","v","Spending — harcama"),
    _w("start","başlamak","v","Starter — başlangıç"),
    _w("stay","kalmak","v","Stay focused — odaklanmaya devam et"),
    _w("stop","durmak","v","Stop and think — dur ve düşün"),
    _w("strong","güçlü","adj","Strength — güç"),
    _w("success","başarı","n","Successful — başarılı"),
    _w("support","desteklemek","v","Supporter — destekçi"),
    _w("suppose","sanmak / varsaymak","v","Supposedly — sözde"),
    _w("sure","emin","adj","Surely — kesinlikle"),
    _w("system","sistem","n","Systematic — sistematik"),
    _w("task","görev","n","Task list — görev listesi"),
    _w("teach","öğretmek","v","Teacher — öğretmen"),
    _w("team","takım","n","Teamwork — takım çalışması"),
    _w("think","düşünmek","v","Thinker — düşünür"),
    _w("tired","yorgun","adj","Tiredness — yorgunluk"),
    _w("together","birlikte","adv","Togetherness — birliktelik"),
    _w("topic","konu","n","Topic sentence — konu cümlesi"),
    _w("travel","seyahat etmek","v","Traveler — gezgin"),
    _w("treat","davranmak / tedavi","v","Treatment — tedavi"),
    _w("trouble","sorun / dert","n","Troublesome — sorunlu"),
    _w("trust","güvenmek","v","Trustworthy — güvenilir"),
    _w("try","denemek","v","Try again — tekrar dene"),
    _w("turn","dönmek / sıra","v","Take turns — sırayla yap"),
    _w("understand","anlamak","v","Understanding — anlayış"),
    _w("unusual","alışılmamış","adj","Unusually — alışılmamış şekilde"),
    _w("upset","üzgün / bozmak","adj","Don't get upset — üzülme"),
    _w("useful","yararlı","adj","Usefulness — kullanışlılık"),
    _w("usually","genellikle","adv","Usual — olağan"),
    _w("valuable","değerli","adj","Value — değer"),
    _w("various","çeşitli","adj","Variety — çeşitlilik"),
    _w("visit","ziyaret etmek","v","Visitor — ziyaretçi"),
    _w("voice","ses / oy","n","Vocal — sesli"),
    _w("wait","beklemek","v","Waiting room — bekleme odası"),
    _w("waste","israf etmek","v","Wasteful — savurgan"),
    _w("weak","zayıf","adj","Weakness — zayıflık"),
    _w("whole","tüm / bütün","adj","Wholesome — sağlıklı"),
    _w("wide","geniş","adj","Width — genişlik"),
    _w("win","kazanmak","v","Winner — kazanan"),
    _w("wish","dilemek / istemek","v","Best wishes — iyi dilekler"),
    _w("wonder","merak etmek","v","Wonderful — harika"),
    _w("worry","endişelenmek","v","Worrying — endişe verici"),
    _w("worth","değer","n","Worthwhile — değerli, emek harcamaya değer"),
    _w("wrong","yanlış","adj","Go wrong — yanlış gitmek"),
    _w("young","genç","adj","Youth — gençlik"),
],

"🔵 B1 Orta": [
    _w("abandon","terk etmek","v","A+bandon: bandonu bırakmak gibi"),
    _w("absorb","emmek / özümsemek","v","A sponge absorbs water — sünger gibi çeker"),
    _w("abstract","soyut","adj","Abstract art — soyut sanat"),
    _w("abuse","kötüye kullanmak","v","Drug abuse — uyuşturucu kötüye kullanımı"),
    _w("academic","akademik","adj","Academia — akademi dünyası"),
    _w("access","erişmek / giriş","v","Accessible — erişilebilir"),
    _w("accurate","doğru / kesin","adj","Accuracy — doğruluk"),
    _w("adapt","uyum sağlamak","v","Adaptation — uyum"),
    _w("adequate","yeterli","adj","Adequately — yeterince"),
    _w("admit","kabul etmek / itiraf","v","Admission — kabul"),
    _w("adopt","benimsemek / evlat edinmek","v","Adoption — evlat edinme"),
    _w("advance","ilerlemek / ilerleme","v","Advanced — ileri düzey"),
    _w("advantage","avantaj / üstünlük","n","Take advantage — avantaj kullan"),
    _w("advertise","reklam yapmak","v","Advertisement — reklam"),
    _w("afford","maddi gücü yetmek","v","Affordable — uygun fiyatlı"),
    _w("aggressive","saldırgan","adj","Aggression — saldırganlık"),
    _w("analyse","analiz etmek","v","Analysis — analiz"),
    _w("annual","yıllık","adj","Annually — yılda bir"),
    _w("anxiety","kaygı / anksiyete","n","Anxious — kaygılı"),
    _w("apparent","açık / belirgin","adj","Apparently — görünüşe göre"),
    _w("apply","başvurmak / uygulamak","v","Application — başvuru"),
    _w("appreciate","takdir etmek","v","Appreciation — takdir"),
    _w("appropriate","uygun","adj","Appropriately — uygun şekilde"),
    _w("approve","onaylamak","v","Approval — onay"),
    _w("aspect","yön / boyut","n","Aspect ratio — en-boy oranı"),
    _w("assist","yardım etmek","v","Assistant — asistan"),
    _w("assume","varsaymak","v","Assumption — varsayım"),
    _w("attach","eklemek / bağlamak","v","Attachment — ek, bağlılık"),
    _w("attempt","denemek / girişim","v","First attempt — ilk deneme"),
    _w("attitude","tutum / davranış","n","Positive attitude — olumlu tutum"),
    _w("attract","çekmek","v","Attraction — çekim"),
    _w("authority","otorite / yetki","n","Authoritative — yetkili"),
    _w("available","mevcut / uygun","adj","Availability — uygunluk"),
    _w("average","ortalama","adj","Average score — ortalama puan"),
    _w("belief","inanç","n","Believe — inanmak"),
    _w("belong","ait olmak","v","Belonging — aidiyet"),
    _w("boundary","sınır","n","Set boundaries — sınır koy"),
    _w("capable","yetenekli","adj","Capability — kapasite"),
    _w("career","kariyer","n","Career path — kariyer yolu"),
    _w("challenge","meydan okuma / zorluk","n","Challenging — zorlu"),
    _w("chapter","bölüm","n","Chapter one — birinci bölüm"),
    _w("characteristic","özellik / karakteristik","n","Characterize — karakterize etmek"),
    _w("circumstance","koşul / durum","n","Under the circumstances — koşullar gereği"),
    _w("collapse","çökmek","v","The bridge collapsed — köprü çöktü"),
    _w("combine","birleştirmek","v","Combination — kombinasyon"),
    _w("communicate","iletişim kurmak","v","Communication — iletişim"),
    _w("community","topluluk","n","Community service — toplum hizmeti"),
    _w("complex","karmaşık","adj","Complexity — karmaşıklık"),
    _w("concern","endişe / ilgilenmek","n","Concerning — endişe verici"),
    _w("confirm","doğrulamak","v","Confirmation — doğrulama"),
    _w("conflict","çatışma","n","Conflict resolution — çatışma çözümü"),
    _w("consequence","sonuç / etki","n","As a consequence — sonuç olarak"),
    _w("consider","düşünmek / değerlendirmek","v","Consideration — değerlendirme"),
    _w("consist","oluşmak","v","Consisting of — oluşan"),
    _w("constant","sabit / sürekli","adj","Constantly — sürekli olarak"),
    _w("context","bağlam","n","In context — bağlamında"),
    _w("contribute","katkıda bulunmak","v","Contribution — katkı"),
    _w("control","kontrol etmek","v","Controller — kontrolcü"),
    _w("convenient","uygun / pratik","adj","Convenience — kolaylık"),
    _w("convince","ikna etmek","v","Convincing — ikna edici"),
    _w("cooperate","iş birliği yapmak","v","Cooperation — iş birliği"),
    _w("cope","başa çıkmak","v","Coping strategy — başa çıkma stratejisi"),
    _w("creative","yaratıcı","adj","Creativity — yaratıcılık"),
    _w("crucial","çok önemli / kritik","adj","Crucially — kritik şekilde"),
    _w("current","güncel / akıntı","adj","Currently — şu an"),
    _w("damage","zarar vermek","v","Damages — tazminat"),
    _w("debate","tartışma / münazara","n","Debatable — tartışmalı"),
    _w("decline","düşmek / reddetmek","v","Declining — azalan"),
    _w("define","tanımlamak","v","Definition — tanım"),
    _w("deliver","teslim etmek","v","Delivery — teslimat"),
    _w("demand","talep etmek","v","Supply and demand — arz ve talep"),
    _w("demonstrate","göstermek / kanıtlamak","v","Demonstration — gösteri"),
    _w("deny","reddetmek / inkâr etmek","v","Denial — inkâr"),
    _w("depend","bağlı olmak","v","Dependent — bağımlı"),
    _w("detail","ayrıntı","n","Detailed — ayrıntılı"),
    _w("determine","belirlemek","v","Determination — kararlılık"),
    _w("diverse","çeşitli / farklı","adj","Diversity — çeşitlilik"),
    _w("document","belgelemek","v","Documentary — belgesel"),
    _w("dominate","hâkim olmak","v","Dominant — baskın"),
    _w("dramatize","dramatize etmek","v","Dramatic — dramatik"),
    _w("economy","ekonomi","n","Economic — ekonomik"),
    _w("effective","etkili","adj","Effectiveness — etkinlik"),
    _w("eliminate","ortadan kaldırmak","v","Elimination — eleme"),
    _w("encourage","teşvik etmek","v","Encouragement — teşvik"),
    _w("enhance","geliştirmek / artırmak","v","Enhancement — iyileştirme"),
    _w("environment","çevre","n","Environmental — çevresel"),
    _w("essential","gerekli / temel","adj","Essentially — özünde"),
    _w("establish","kurmak / oluşturmak","v","Establishment — kurum"),
    _w("evaluate","değerlendirmek","v","Evaluation — değerlendirme"),
    _w("evidence","kanıt / delil","n","Evidence-based — kanıta dayalı"),
    _w("evolve","evrimleşmek / gelişmek","v","Evolution — evrim"),
    _w("exactly","tam olarak","adv","Exact — tam, kesin"),
    _w("expand","genişlemek","v","Expansion — genişleme"),
    _w("expense","masraf","n","Expensive — pahalı"),
    _w("experiment","deney yapmak","v","Experimental — deneysel"),
    _w("express","ifade etmek","v","Expression — ifade"),
    _w("extend","uzatmak","v","Extension — uzantı"),
    _w("extreme","aşırı","adj","Extremely — son derece"),
    _w("factor","etken / faktör","n","Risk factor — risk faktörü"),
    _w("feature","özellik","n","Featured — öne çıkan"),
    _w("flexible","esnek","adj","Flexibility — esneklik"),
    _w("formal","resmi","adj","Formality — resmiyet"),
    _w("frequent","sık","adj","Frequently — sık sık"),
    _w("function","işlev / çalışmak","n","Functional — işlevsel"),
    _w("fund","fon / finansman","n","Fundraising — fon toplama"),
    _w("generate","üretmek / oluşturmak","v","Generation — jenerasyon"),
    _w("global","küresel","adj","Globalization — küreselleşme"),
    _w("gradual","kademeli","adj","Gradually — yavaş yavaş"),
    _w("guarantee","garanti etmek","v","Guaranteed — garantili"),
    _w("highlight","vurgulamak","v","Highlighted — vurgulanan"),
    _w("identify","tanımlamak / tespit etmek","v","Identity — kimlik"),
    _w("ignore","görmezden gelmek","v","Ignorance — cehalet"),
    _w("impact","etki","n","High impact — yüksek etki"),
    _w("implement","uygulamak","v","Implementation — uygulama"),
    _w("imply","ima etmek","v","Implication — ima, çıkarım"),
    _w("indicate","göstermek","v","Indication — gösterge"),
    _w("individual","bireysel / kişi","adj","Individualism — bireycilik"),
    _w("influence","etkilemek / etki","v","Influential — etkili"),
    _w("inform","bilgilendirmek","v","Information — bilgi"),
    _w("initiative","girişim","n","Take the initiative — inisiyatif al"),
    _w("innovate","yenilik yapmak","v","Innovation — yenilik"),
    _w("inspire","ilham vermek","v","Inspiration — ilham"),
    _w("intend","niyetlenmek","v","Intention — niyet"),
    _w("interpret","yorumlamak","v","Interpretation — yorum"),
    _w("investigate","araştırmak","v","Investigation — soruşturma"),
    _w("involve","içermek / katmak","v","Involvement — katılım"),
    _w("issue","konu / sorun","n","Raise an issue — sorun gündeme getir"),
    _w("justify","haklı çıkarmak","v","Justification — gerekçe"),
    _w("lack","eksiklik / yoksun olmak","n","Lacking — eksik olan"),
    _w("launch","başlatmak / fırlatmak","v","Product launch — ürün lansmanı"),
    _w("layer","katman","n","Layered — katmanlı"),
    _w("limit","sınırlamak","v","Limitation — sınırlama"),
    _w("maintain","sürdürmek","v","Maintenance — bakım"),
    _w("major","büyük / önemli","adj","Majority — çoğunluk"),
    _w("mention","bahsetmek","v","Worth mentioning — bahsetmeye değer"),
    _w("method","yöntem","n","Methodology — metodoloji"),
    _w("minor","küçük / önemsiz","adj","Minority — azınlık"),
    _w("monitor","izlemek","v","Monitoring — izleme"),
    _w("motivate","motive etmek","v","Motivation — motivasyon"),
    _w("negative","olumsuz","adj","Negativity — olumsuzluk"),
    _w("obtain","elde etmek","v","Obtainable — elde edilebilir"),
    _w("obvious","açık / bariz","adj","Obviously — açıkça"),
    _w("occur","meydana gelmek","v","Occurrence — olay"),
    _w("oppose","karşı çıkmak","v","Opposition — muhalefet"),
    _w("outcome","sonuç","n","Desired outcome — istenen sonuç"),
    _w("overcome","üstesinden gelmek","v","Overcoming challenges — zorlukların üstesinden gelme"),
    _w("participate","katılmak","v","Participation — katılım"),
    _w("perceive","algılamak","v","Perception — algı"),
    _w("perform","gerçekleştirmek","v","Performance — performans"),
    _w("perspective","bakış açısı","n","Different perspectives — farklı bakış açıları"),
    _w("persuade","ikna etmek","v","Persuasion — ikna"),
    _w("physical","fiziksel","adj","Physically — fiziksel olarak"),
    _w("policy","politika","n","Policy maker — politika yapıcı"),
    _w("positive","olumlu","adj","Positivity — olumlu düşünce"),
    _w("potential","potansiyel","n","Potentially — potansiyel olarak"),
    _w("practical","pratik","adj","Practically — pratik olarak"),
    _w("precise","kesin / hassas","adj","Precision — hassasiyet"),
    _w("predict","tahmin etmek","v","Prediction — tahmin"),
    _w("primary","birincil / ana","adj","Primarily — esas olarak"),
    _w("priority","öncelik","n","Set priorities — öncelik belirle"),
    _w("process","süreç","n","Processing — işleme"),
    _w("profit","kâr","n","Profitable — kârlı"),
    _w("promote","desteklemek / tanıtmak","v","Promotion — terfi"),
    _w("property","mülk / özellik","n","Property rights — mülkiyet hakları"),
    _w("propose","önermek","v","Proposal — teklif"),
    _w("pursue","takip etmek / peşinde olmak","v","Pursuit of happiness — mutluluğun peşinde"),
    _w("react","tepki vermek","v","Reaction — tepki"),
    _w("refer","atıfta bulunmak","v","Reference — referans"),
    _w("reflect","yansıtmak","v","Reflection — yansıma"),
    _w("relate","ilgili olmak","v","Relationship — ilişki"),
    _w("relevant","ilgili / uygun","adj","Relevance — uygunluk"),
    _w("reliable","güvenilir","adj","Reliability — güvenilirlik"),
    _w("require","gerektirmek","v","Requirement — gereklilik"),
    _w("research","araştırmak","v","Researcher — araştırmacı"),
    _w("resource","kaynak","n","Natural resources — doğal kaynaklar"),
    _w("respond","yanıt vermek","v","Response — yanıt"),
    _w("reveal","ortaya çıkarmak","v","Revelation — vahiy, ortaya çıkma"),
    _w("review","gözden geçirmek","v","Peer review — akran değerlendirmesi"),
    _w("revise","gözden geçirmek / düzeltmek","v","Revision — revizyon"),
    _w("reward","ödüllendirmek","v","Rewarding — ödüllendirici"),
    _w("route","güzergâh","n","Routing — yönlendirme"),
    _w("scale","ölçek / büyüklük","n","Large-scale — büyük ölçekli"),
    _w("schedule","program / çizelge","n","Scheduled — programlanmış"),
    _w("select","seçmek","v","Selection — seçim"),
    _w("significant","önemli","adj","Significance — önem"),
    _w("similar","benzer","adj","Similarity — benzerlik"),
    _w("situation","durum","n","Situational — durumsal"),
    _w("society","toplum","n","Social — sosyal"),
    _w("source","kaynak","n","Source code — kaynak kod"),
    _w("specific","belirli / özel","adj","Specifically — özellikle"),
    _w("strategy","strateji","n","Strategic — stratejik"),
    _w("structure","yapı","n","Structural — yapısal"),
    _w("sufficient","yeterli","adj","Sufficiently — yeterince"),
    _w("suggest","önermek","v","Suggestion — öneri"),
    _w("summarize","özetlemek","v","Summary — özet"),
    _w("survey","anket / araştırma","n","Survey results — anket sonuçları"),
    _w("sustainable","sürdürülebilir","adj","Sustainability — sürdürülebilirlik"),
    _w("symbol","sembol","n","Symbolic — sembolik"),
    _w("target","hedef","n","Target audience — hedef kitle"),
    _w("tend","eğiliminde olmak","v","Tendency — eğilim"),
    _w("therefore","bu nedenle","adv","Therefore — bu yüzden"),
    _w("threat","tehdit","n","Threatening — tehdit edici"),
    _w("throughout","boyunca","prep","Throughout the year — yıl boyunca"),
    _w("tradition","gelenek","n","Traditional — geleneksel"),
    _w("transfer","aktarmak","v","Transfer of power — iktidar devri"),
    _w("transform","dönüştürmek","v","Transformation — dönüşüm"),
    _w("trend","eğilim / trend","n","Current trends — güncel trendler"),
    _w("typical","tipik","adj","Typically — tipik olarak"),
    _w("ultimately","sonuçta","adv","Ultimate — nihai"),
    _w("unique","benzersiz","adj","Uniqueness — benzersizlik"),
    _w("update","güncellemek","v","Up-to-date — güncel"),
    _w("utilize","kullanmak / yararlanmak","v","Utilization — kullanım"),
    _w("valid","geçerli","adj","Validity — geçerlilik"),
    _w("variety","çeşitlilik","n","Varied — çeşitli"),
    _w("vast","geniş / büyük","adj","Vastly — büyük ölçüde"),
    _w("visible","görünür","adj","Visibility — görünürlük"),
    _w("vital","hayati / çok önemli","adj","Vitality — canlılık"),
    _w("voluntary","gönüllü","adj","Volunteer — gönüllü"),
    _w("widespread","yaygın","adj","Widespread use — yaygın kullanım"),
    _w("allege","iddia etmek","v","Allegedly — iddiaya göre"),
    _w("cease","durmak / son vermek","v","Cease fire — ateşkes"),
    _w("comprehend","kavramak","v","Fail to comprehend — kavrayamamak"),
    _w("conceal","gizlemek","v","Conceal the truth — gerçeği gizlemek"),
    _w("deplete","tüketmek","v","Deplete resources — kaynakları tüketmek"),
    _w("emit","salmak / yaymak","v","Emit carbon — karbon salmak"),
    _w("expertise","uzmanlık","n","Domain expertise — alan uzmanlığı"),
    _w("extinction","yok oluş","n","Mass extinction — kitlesel yok oluş"),
    _w("infrastructure","altyapı","n","Transport infrastructure — ulaşım altyapısı"),
    _w("conscientious","vicdanlı / özenli","adj","Conscientious worker — özenli çalışan"),
    _w("detain","gözaltına almak","v","Detained for questioning — sorgu için gözaltına alınmak"),
    _w("eligible","hak kazanmış / uygun","adj","Eligible to vote — oy kullanmaya hak kazanmış"),
    _w("estimate","tahmin etmek","v","Rough estimate — kaba tahmin"),
    _w("gradually","yavaş yavaş","adv","Gradually improve — yavaş yavaş iyileşmek"),
    _w("initial","başlangıçtaki / ilk","adj","Initial reaction — ilk tepki"),
    _w("procedure","prosedür / işlem","n","Standard procedure — standart prosedür"),
    _w("consume","tüketmek","v","Consume resources — kaynakları tüketmek"),
    _w("distort","çarpıtmak","v","Distort the facts — gerçekleri çarpıtmak"),
    _w("thereby","böylece","adv","Thereby reducing — böylece azaltan"),
    _w("whereas","oysa ki","conj","Whereas others — oysa diğerleri"),
],

"🟡 B2 Orta-İleri": [
    _w("abolish","kaldırmak / lağvetmek","v","A+bolish: tamamen sil — abolish slavery"),
    _w("accelerate","hızlandırmak","v","Accelerator — gaz pedalı"),
    _w("accommodate","barındırmak / uyum sağlamak","v","Accommodation — konaklama"),
    _w("accomplish","başarmak","v","Accomplishment — başarı"),
    _w("accumulate","birikmek","v","Accumulation — birikim"),
    _w("acknowledge","kabul etmek / tanımak","v","Acknowledgment — kabul"),
    _w("acquisition","edinim / elde etme","n","Language acquisition — dil edinimi"),
    _w("address","ele almak","v","Address a problem — sorunu ele al"),
    _w("adjacent","bitişik / yanındaki","adj","Adjacent rooms — bitişik odalar"),
    _w("advocate","savunmak / taraftar","v","Advocacy — savunuculuk"),
    _w("aggregate","toplamak / toplam","v","Aggregate data — toplu veri"),
    _w("alienate","yabancılaştırmak","v","Alienation — yabancılaşma"),
    _w("allocate","tahsis etmek","v","Allocation — tahsis"),
    _w("ambiguous","belirsiz / muğlak","adj","Ambiguity — belirsizlik"),
    _w("analogy","benzetme / analoji","n","By analogy — benzetmeyle"),
    _w("anticipate","öngörmek","v","Anticipation — öngörü"),
    _w("arbitrary","keyfi","adj","Arbitrarily — keyfi olarak"),
    _w("articulate","açık ifade etmek","v","Articulation — ifade"),
    _w("assert","iddia etmek","v","Assertion — iddia"),
    _w("assess","değerlendirmek","v","Assessment — değerlendirme"),
    _w("attribute","özellik / atfetmek","n","Attributable — atfedilebilir"),
    _w("autonomous","özerk / bağımsız","adj","Autonomy — özerklik"),
    _w("bias","önyargı / taraflılık","n","Biased — taraflı"),
    _w("broaden","genişletmek","v","Broad — geniş"),
    _w("capacity","kapasite / yetenek","n","At full capacity — tam kapasite"),
    _w("clarify","açıklamak / netleştirmek","v","Clarification — açıklama"),
    _w("cognitive","bilişsel","adj","Cognitive ability — bilişsel yetenek"),
    _w("coherent","tutarlı / bütünlüklü","adj","Coherence — tutarlılık"),
    _w("coincide","çakışmak / denk gelmek","v","Coincidence — tesadüf"),
    _w("collaborate","iş birliği yapmak","v","Collaboration — iş birliği"),
    _w("competent","yetkin / becerikli","adj","Competence — yetkinlik"),
    _w("complement","tamamlamak","v","Complementary — tamamlayıcı"),
    _w("compel","zorlamak","v","Compelling — zorlayıcı, ilgi çekici"),
    _w("comprehensive","kapsamlı","adj","Comprehension — anlama"),
    _w("comprise","oluşmak / içermek","v","Comprising — içeren"),
    _w("concede","kabul etmek / ödün vermek","v","Concession — ödün"),
    _w("concise","özlü / kısa","adj","Concisely — kısaca"),
    _w("confine","sınırlamak / hapsetmek","v","Confined — sınırlı"),
    _w("consolidate","güçlendirmek / pekiştirmek","v","Consolidation — pekiştirme"),
    _w("contend","mücadele etmek / ileri sürmek","v","Contention — iddia"),
    _w("contradict","çelişmek","v","Contradiction — çelişki"),
    _w("controversial","tartışmalı","adj","Controversy — tartışma"),
    _w("convey","iletmek","v","Conveying a message — mesaj iletme"),
    _w("correlate","ilişkilendirmek","v","Correlation — korelasyon"),
    _w("counterpart","muadil / karşılık","n","Foreign counterpart — yabancı muadil"),
    _w("critique","eleştirmek","v","Critical — eleştirel"),
    _w("deduce","çıkarsamak","v","Deduction — çıkarım"),
    _w("deficit","açık / eksiklik","n","Budget deficit — bütçe açığı"),
    _w("deliberate","kasıtlı / düşünülmüş","adj","Deliberately — kasıtlı olarak"),
    _w("deploy","konuşlandırmak","v","Deployment — konuşlanma"),
    _w("derive","türetmek / elde etmek","v","Derived from — kaynağı olan"),
    _w("discriminate","ayrım yapmak","v","Discrimination — ayrımcılık"),
    _w("disrupt","bozmak / sekteye uğratmak","v","Disruption — kesinti"),
    _w("distinct","belirgin / farklı","adj","Distinction — ayrım"),
    _w("distinguish","ayırt etmek","v","Distinguished — seçkin"),
    _w("dynamic","dinamik","adj","Dynamics — dinamikler"),
    _w("elaborate","ayrıntılandırmak","v","Elaboration — ayrıntı"),
    _w("emerge","ortaya çıkmak","v","Emergence — ortaya çıkış"),
    _w("emphasize","vurgulamak","v","Emphasis — vurgu"),
    _w("empirical","deneysel / ampirik","adj","Empirically — deneysel olarak"),
    _w("enforce","uygulamak / zorlamak","v","Enforcement — uygulama"),
    _w("enormous","muazzam / çok büyük","adj","Enormously — çok büyük ölçüde"),
    _w("ensure","sağlamak / güvence altına almak","v","Ensuring — sağlayan"),
    _w("enumerate","saymak / listelemek","v","Enumeration — listeleme"),
    _w("ethical","etik / ahlaki","adj","Ethics — etik"),
    _w("exceed","aşmak","v","Exceeding — aşan"),
    _w("exclude","dışlamak","v","Exclusion — dışlanma"),
    _w("explicit","açık / net","adj","Explicitly — açıkça"),
    _w("expose","maruz bırakmak","v","Exposure — maruz kalma"),
    _w("facilitate","kolaylaştırmak","v","Facilitation — kolaylaştırma"),
    _w("fluctuate","dalgalanmak","v","Fluctuation — dalgalanma"),
    _w("formulate","formüle etmek","v","Formulation — formülasyon"),
    _w("foster","beslemek / teşvik etmek","v","Fostering — yetiştirme"),
    _w("framework","çerçeve","n","Conceptual framework — kavramsal çerçeve"),
    _w("fundamental","temel / esas","adj","Fundamentally — temelde"),
    _w("hypothesis","hipotez","n","Hypothetical — varsayımsal"),
    _w("illustrate","örneklemek / resmetmek","v","Illustration — resim / örnek"),
    _w("implicit","örtük / ima edilen","adj","Implicitly — zımnen"),
    _w("impose","dayatmak","v","Imposition — dayatma"),
    _w("incorporate","bünyesine katmak","v","Incorporation — dahil etme"),
    _w("inevitable","kaçınılmaz","adj","Inevitably — kaçınılmaz olarak"),
    _w("infer","çıkarım yapmak","v","Inference — çıkarım"),
    _w("inhibit","engellemek","v","Inhibition — engelleme"),
    _w("innate","doğuştan gelen","adj","Innately — doğuştan"),
    _w("instance","örnek / durum","n","For instance — örneğin"),
    _w("integrate","bütünleştirmek","v","Integration — entegrasyon"),
    _w("interact","etkileşmek","v","Interaction — etkileşim"),
    _w("intrinsic","içsel / doğasında olan","adj","Intrinsically — doğası gereği"),
    _w("liberal","liberal / özgürlükçü","adj","Liberalism — liberalizm"),
    _w("likewise","benzer şekilde","adv","Likewise, we can — benzer şekilde yapabiliriz"),
    _w("manipulate","manipüle etmek","v","Manipulation — manipülasyon"),
    _w("mechanism","mekanizma","n","Defense mechanism — savunma mekanizması"),
    _w("mediate","arabuluculuk etmek","v","Mediation — arabuluculuk"),
    _w("migrate","göç etmek","v","Migration — göç"),
    _w("moderate","ılımlı / orta","adj","Moderation — ılımlılık"),
    _w("mutual","karşılıklı","adj","Mutually — karşılıklı olarak"),
    _w("notion","kavram / fikir","n","The notion that — fikri"),
    _w("novel","yeni / roman","adj","Novelty — yenilik"),
    _w("objective","nesnel / hedef","adj","Objectivity — nesnellik"),
    _w("omit","atlamak / dışarıda bırakmak","v","Omission — atlama"),
    _w("ongoing","devam eden","adj","Ongoing project — devam eden proje"),
    _w("optimistic","iyimser","adj","Optimism — iyimserlik"),
    _w("orient","yönlendirmek","v","Orientation — yönelim"),
    _w("oversee","denetlemek","v","Oversight — denetim"),
    _w("paradigm","paradigma / örüntü","n","Paradigm shift — paradigma kayması"),
    _w("partially","kısmen","adv","Partial — kısmi"),
    _w("persist","ısrar etmek / devam etmek","v","Persistence — ısrar"),
    _w("phenomenon","fenomen / olay","n","Natural phenomenon — doğal fenomen"),
    _w("plausible","makul / inandırıcı","adj","Plausibly — makul şekilde"),
    _w("predominantly","ağırlıklı olarak","adv","Predominant — hâkim"),
    _w("premise","öncül / varsayım","n","On the premise that — varsayımıyla"),
    _w("prevalent","yaygın","adj","Prevalence — yaygınlık"),
    _w("prohibit","yasaklamak","v","Prohibition — yasak"),
    _w("prone","eğilimli","adj","Prone to error — hata yapmaya eğilimli"),
    _w("qualified","nitelikli","adj","Qualification — nitelik"),
    _w("quantify","sayısallaştırmak","v","Quantifiable — ölçülebilir"),
    _w("questionnaire","anket formu","n","Fill in the questionnaire — anketi doldur"),
    _w("rational","mantıklı / rasyonel","adj","Rationality — akılcılık"),
    _w("reinforce","pekiştirmek","v","Reinforcement — pekiştirme"),
    _w("reject","reddetmek","v","Rejection — ret"),
    _w("resemble","benzemek","v","Resemblance — benzerlik"),
    _w("restrict","kısıtlamak","v","Restriction — kısıtlama"),
    _w("retain","muhafaza etmek","v","Retention — elde tutma"),
    _w("revoke","iptal etmek","v","Revocation — iptal"),
    _w("rigid","katı / esnek olmayan","adj","Rigidity — katılık"),
    _w("scope","kapsam","n","Scope of work — iş kapsamı"),
    _w("sequence","dizi / sıra","n","Sequential — sıralı"),
    _w("simultaneously","eş zamanlı olarak","adv","Simultaneous — eş zamanlı"),
    _w("spectrum","spektrum / yelpaze","n","Wide spectrum — geniş yelpaze"),
    _w("speculate","spekülasyon yapmak","v","Speculation — spekülasyon"),
    _w("stability","istikrar","n","Stable — istikrarlı"),
    _w("statistic","istatistik","n","Statistical — istatistiksel"),
    _w("stimulate","uyarmak / teşvik etmek","v","Stimulation — uyarı"),
    _w("subordinate","ast / ikincil","adj","Subordination — bağımlılık"),
    _w("substitute","ikame / yerine koymak","v","Substitution — ikame"),
    _w("suppress","bastırmak","v","Suppression — baskılama"),
    _w("synthesis","sentez","n","Synthesize — sentezlemek"),
    _w("systematic","sistematik","adj","Systematically — sistematik olarak"),
    _w("tension","gerilim","n","Tension between — arasındaki gerilim"),
    _w("terminate","sona erdirmek","v","Termination — fesih"),
    _w("theoretical","teorik","adj","Theoretically — teorik olarak"),
    _w("transition","geçiş","n","Transitional — geçiş dönemine ait"),
    _w("transmit","iletmek","v","Transmission — iletim"),
    _w("underlying","altta yatan","adj","Underlying cause — altta yatan neden"),
    _w("undermine","zayıflatmak","v","Undermining trust — güveni zedeleme"),
    _w("unify","birleştirmek","v","Unification — birleşme"),
    _w("validate","doğrulamak","v","Validation — doğrulama"),
    _w("variable","değişken","n","Variables — değişkenler"),
    _w("verify","doğrulamak","v","Verification — doğrulama"),
    _w("virtual","sanal","adj","Virtually — neredeyse / sanal olarak"),
    _w("yield","vermek / getiri","v","High yield — yüksek verim"),
    _w("coherence","tutarlılık","n","Coherent argument — tutarlı argüman"),
    _w("implication","çıkarım / ima","n","Broad implications — geniş çaplı sonuçlar"),
    _w("correlation","korelasyon","n","Strong correlation — güçlü korelasyon"),
    _w("deviation","sapma","n","Standard deviation — standart sapma"),
    _w("hierarchy","hiyerarşi","n","Hierarchical — hiyerarşik"),
    _w("incentive","teşvik","n","Financial incentive — mali teşvik"),
    _w("inference","çıkarım","n","Logical inference — mantıksal çıkarım"),
    _w("innovation","yenilik","n","Innovative — yenilikçi"),
    _w("integrity","dürüstlük / bütünlük","n","Academic integrity — akademik dürüstlük"),
    _w("legislation","mevzuat / yasa","n","Legislative — yasama"),
    _w("momentum","ivme / momentum","n","Gain momentum — ivme kazanmak"),
    _w("narrative","anlatı","n","Narrative structure — anlatı yapısı"),
    _w("norm","norm / kural","n","Social norms — sosyal normlar"),
    _w("perception","algı","n","Public perception — kamuoyu algısı"),
    _w("proportion","orantı","n","In proportion to — oranla"),
    _w("protocol","protokol","n","Safety protocol — güvenlik protokolü"),
    _w("revenue","gelir","n","Revenue stream — gelir akışı"),
    _w("rhetoric","retorik / söz sanatı","n","Rhetorical — retorik"),
    _w("sector","sektör","n","Public sector — kamu sektörü"),
    _w("stereotype","kalıp yargı","n","Stereotypical — klişe"),
    _w("subjective","öznel","adj","Subjectivity — öznellik"),
    _w("abolition","kaldırma / lağvetme","n","Abolition of slavery — köleliğin kaldırılması"),
    _w("abstraction","soyutlama","n","Level of abstraction — soyutlama düzeyi"),
    _w("accountability","hesap verebilirlik","n","Public accountability — kamuya hesap verme"),
    _w("accumulation","birikim","n","Capital accumulation — sermaye birikimi"),
    _w("adherence","bağlılık","n","Adherence to rules — kurallara bağlılık"),
    _w("affiliation","bağlantı / üyelik","n","Political affiliation — siyasi bağlantı"),
    _w("alienation","yabancılaşma","n","Social alienation — toplumsal yabancılaşma"),
    _w("allegiance","sadakat","n","Pledge allegiance — sadakat yemini"),
    _w("amendment","değişiklik","n","Constitutional amendment — anayasa değişikliği"),
    _w("amplify","büyütmek / güçlendirmek","v","Amplify the message — mesajı güçlendirmek"),
    _w("anecdotal","anekdota dayalı","adj","Anecdotal evidence — anekdot kanıt"),
    _w("anonymity","anonimlik","n","Online anonymity — çevrimiçi anonimlik"),
    _w("apprehension","endişe","n","Widespread apprehension — yaygın endişe"),
    _w("archetype","arketip","n","Cultural archetype — kültürel arketip"),
    _w("assertion","iddia","n","Bold assertion — cesur iddia"),
    _w("assimilation","asimilasyon","n","Cultural assimilation — kültürel asimilasyon"),
    _w("attrition","yıpranma","n","War of attrition — yıpratma savaşı"),
    _w("austerity","kemer sıkma","n","Austerity measures — kemer sıkma tedbirleri"),
    _w("benchmark","kıyas noktası","n","Industry benchmark — sektör standardı"),
    _w("bolster","desteklemek / güçlendirmek","v","Bolster confidence — güveni pekiştirmek"),
    _w("bureaucracy","bürokrasi","n","Bureaucratic delay — bürokratik gecikme"),
    _w("candour","açık sözlülük","n","Refreshing candour — ferahlatıcı açıksözlülük"),
    _w("causality","nedensellik","n","Causality in research — araştırmada nedensellik"),
    _w("centralize","merkezileştirmek","v","Centralize control — kontrolü merkezileştirmek"),
    _w("chronological","kronolojik","adj","Chronological order — kronolojik sıra"),
    _w("circulation","dolaşım","n","Blood circulation — kan dolaşımı"),
    _w("civic","yurttaşlıkla ilgili","adj","Civic engagement — yurttaşlık katılımı"),
    _w("coexistence","bir arada yaşama","n","Peaceful coexistence — barış içinde yaşama"),
    _w("cohesion","uyum","n","Team cohesion — takım uyumu"),
    _w("commodity","emtia","n","Commodity market — emtia piyasası"),
    _w("compliance","uyum","n","Regulatory compliance — mevzuat uyumu"),
    _w("conceptual","kavramsal","adj","Conceptual model — kavramsal model"),
    _w("concurrent","eş zamanlı","adj","Concurrent tasks — eşzamanlı görevler"),
    _w("conformity","uyumluluk","n","Social conformity — toplumsal uyumluluk"),
    _w("conjecture","tahmin / sanı","n","Pure conjecture — saf tahmin"),
    _w("consensus","uzlaşma","n","Build consensus — uzlaşma sağlamak"),
    _w("constraints","kısıtlamalar","n","Financial constraints — mali kısıtlamalar"),
    _w("contemplate","düşünmek","v","Contemplate options — seçenekleri düşünmek"),
    _w("contention","tartışma","n","Point of contention — tartışma noktası"),
    _w("contingency","olası durum","n","Contingency plan — acil plan"),
    _w("credibility","güvenilirlik","n","Journalistic credibility — gazetecilik güvenilirliği"),
    _w("culminate","doruğa ulaşmak","v","Culminate in success — başarıyla sonuçlanmak"),
    _w("cumulative","birikimli","adj","Cumulative effect — birikimli etki"),
    _w("cynicism","şüphecilik","n","Growing cynicism — artan şüphecilik"),
    _w("decentralize","ademi merkezileştirmek","v","Decentralize decision-making — karar almayı dağıtmak"),
    _w("deception","aldatma","n","Deliberate deception — kasıtlı aldatma"),
    _w("deficiency","eksiklik","n","Vitamin deficiency — vitamin eksikliği"),
    _w("degradation","bozulma","n","Soil degradation — toprak bozulması"),
    _w("deliberation","müzakere","n","Careful deliberation — dikkatli müzakere"),
    _w("demographic","demografik","adj","Demographic shift — demografik değişim"),
    _w("deprivation","yoksunluk","n","Sleep deprivation — uyku yoksunluğu"),
    _w("detachment","mesafe / soğukkanlılık","n","Emotional detachment — duygusal mesafe"),
    _w("deterioration","kötüleşme","n","Condition deterioration — durum kötüleşmesi"),
    _w("dictatorship","diktatörlük","n","Fall of dictatorship — diktatörlüğün çöküşü"),
    _w("dilemma","ikilem","n","Moral dilemma — ahlaki ikilem"),
    _w("disparity","eşitsizlik","n","Wealth disparity — servet eşitsizliği"),
    _w("dissent","muhalefet","n","Suppress dissent — muhalefeti bastırmak"),
    _w("distortion","çarpıtma","n","Media distortion — medya çarpıtması"),
    _w("divergence","ayrışma","n","Ideological divergence — ideolojik ayrışma"),
    _w("dogma","dogma","n","Challenge dogma — dogmayı sorgulamak"),
    _w("domination","egemenlik","n","Market domination — pazar egemenliği"),
    _w("downfall","çöküş","n","Cause downfall — çöküşe yol açmak"),
    _w("duality","ikililik","n","Inherent duality — içsel ikililik"),
    _w("dysfunction","işlev bozukluğu","n","Institutional dysfunction — kurumsal işlev bozukluğu"),
    _w("evasion","kaçınma","n","Tax evasion — vergi kaçakçılığı"),
    _w("exaggeration","abartma","n","Gross exaggeration — büyük abartma"),
    _w("exploitation","sömürü","n","Labour exploitation — işçi sömürüsü"),
    _w("fallout","yansıma / sonuç","n","Political fallout — siyasi yansıma"),
    _w("fragmentation","parçalanma","n","Market fragmentation — pazar parçalanması"),
    _w("friction","sürtüşme","n","Social friction — toplumsal sürtüşme"),
    _w("governance","yönetim","n","Corporate governance — kurumsal yönetişim"),
    _w("grievance","şikâyet","n","Address grievances — şikâyetleri çözmek"),
    _w("groundwork","zemin / temel","n","Lay the groundwork — zemini hazırlamak"),
    _w("ideology","ideoloji","n","Dominant ideology — baskın ideoloji"),
    _w("immersion","daldırma / yoğunlaşma","n","Full immersion — tam daldırma"),
    _w("imperative","zorunluluk","n","Moral imperative — ahlaki zorunluluk"),
    _w("inception","başlangıç","n","Since inception — başından beri"),
    _w("indicator","gösterge","n","Key indicator — temel gösterge"),
    _w("inequality","eşitsizlik","n","Income inequality — gelir eşitsizliği"),
    _w("insecurity","güvensizlik","n","Economic insecurity — ekonomik güvensizlik"),
    _w("insight","içgörü","n","Key insight — temel içgörü"),
    _w("instability","istikrarsızlık","n","Regional instability — bölgesel istikrarsızlık"),
    _w("institution","kurum","n","Democratic institution — demokratik kurum"),
    _w("interdependence","karşılıklı bağımlılık","n","Global interdependence — küresel bağımlılık"),
    _w("legitimacy","meşruiyet","n","Political legitimacy — siyasi meşruiyet"),
    _w("liberation","kurtuluş","n","Liberation struggle — kurtuluş mücadelesi"),
    _w("magnitude","büyüklük","n","Magnitude of impact — etkinin büyüklüğü"),
    _w("manifestation","tezahür","n","Clear manifestation — açık tezahür"),
    _w("manipulation","manipülasyon","n","Data manipulation — veri manipülasyonu"),
    _w("marginalisation","marjinalleştirme","n","Social marginalisation — toplumsal dışlanma"),
    _w("mediation","arabuluculuk","n","Peace mediation — barış arabuluculuğu"),
    _w("meritocracy","liyakat sistemi","n","True meritocracy — gerçek liyakat"),
    _w("methodology","metodoloji","n","Scientific methodology — bilimsel metodoloji"),
    _w("mobilization","seferberlik","n","Political mobilization — siyasi seferberlik"),
    _w("moderation","ılımlılık","n","In moderation — ölçülü olarak"),
    _w("monopoly","tekel","n","State monopoly — devlet tekeli"),
    _w("objectivity","nesnellik","n","Maintain objectivity — nesnelliği korumak"),
    _w("obsolescence","eskime","n","Planned obsolescence — planlı eskime"),
    _w("oppression","baskı","n","End oppression — baskıya son vermek"),
    _w("optimisation","optimizasyon","n","Performance optimisation — performans optimizasyonu"),
    _w("partisanship","partizanlık","n","Rise of partisanship — partizanlığın yükselişi"),
    _w("polarisation","kutuplaşma","n","Social polarisation — toplumsal kutuplaşma"),
    _w("pragmatism","pragmatizm","n","Embrace pragmatism — pragmatizmi benimsemek"),
    _w("precondition","ön koşul","n","Necessary precondition — gerekli ön koşul"),
    _w("prerogative","ayrıcalık","n","Executive prerogative — yürütme ayrıcalığı"),
    _w("propaganda","propaganda","n","Wartime propaganda — savaş zamanı propagandası"),
    _w("reconciliation","uzlaşma","n","Seek reconciliation — uzlaşma aramak"),
    _w("redistribution","yeniden dağıtım","n","Income redistribution — gelir yeniden dağıtımı"),
    _w("referendum","referandum","n","Call a referendum — referandum çağrısı"),
    _w("repercussion","yansıma","n","Wide repercussions — geniş kapsamlı yansımalar"),
    _w("representation","temsil","n","Political representation — siyasi temsil"),
    _w("sovereignty","egemenlik","n","State sovereignty — devlet egemenliği"),
    _w("transparency","şeffaflık","n","Corporate transparency — kurumsal şeffaflık"),
    _w("upheaval","altüst oluş","n","Social upheaval — toplumsal çalkantı"),
    _w("utilitarian","faydacı","adj","Utilitarian ethics — faydacı etik"),
    _w("vulnerability","kırılganlık","n","Financial vulnerability — finansal kırılganlık"),
    _w("scrutiny","denetim / inceleme","n","Public scrutiny — kamuoyu denetimi"),
    _w("rationale","gerekçe / mantık","n","Underlying rationale — altta yatan gerekçe"),
    _w("proponent","savunucu / taraftar","n","Strong proponent — güçlü savunucu"),
    _w("precedent","emsal / örnek","n","Set a precedent — emsal oluşturmak"),
    _w("nuance","nüans / ince fark","n","Important nuance — önemli nüans"),
    _w("nexus","bağlantı / merkez","n","Central nexus — merkezi bağlantı"),
    _w("leverage","kaldıraç / etki","n","Use as leverage — kaldıraç olarak kullanmak"),
    _w("hallmark","karakteristik özellik","n","Hallmark of quality — kalitenin özelliği"),
    _w("endemic","yaygın / endemik","adj","Endemic corruption — yaygın yolsuzluk"),
    _w("dimension","boyut","n","Multiple dimensions — çoklu boyutlar"),
    _w("ambivalence","kararsızlık","n","Show ambivalence — kararsızlık göstermek"),
    _w("accessibility","erişilebilirlik","n","Improve accessibility — erişilebilirliği artırmak"),
    _w("abide","uymak","v","Abide by rules — kurallara uymak"),
    _w("adverse","olumsuz / zararlı","adj","Adverse effects — olumsuz etkiler"),
    _w("alter","değiştirmek","v","Alter the outcome — sonucu değiştirmek"),
    _w("collateral","teminat / yan","adj","Collateral damage — yan hasar"),
    _w("complicit","suç ortağı","adj","Complicit in the scheme — plana ortak"),
    _w("consequential","sonuçları önemli","adj","Highly consequential — çok önemli sonuçları olan"),
    _w("de facto","fiili / eylemli","adj","De facto leader — fiili lider"),
    _w("deter","caydırmak","v","Deter crime — suçu caydırmak"),
    _w("disproportionate","orantısız","adj","Disproportionate response — orantısız tepki"),
    _w("encapsulate","özetlemek / kapsamak","v","Encapsulate the idea — fikri özetlemek"),
    _w("entrenched","yerleşik / köklü","adj","Entrenched inequality — köklü eşitsizlik"),
    _w("evolving","gelişen / değişen","adj","Rapidly evolving — hızla gelişen"),
    _w("exclusive","münhasır / sadece","adj","Exclusive rights — münhasır haklar"),
    _w("expedite","hızlandırmak","v","Expedite the process — süreci hızlandırmak"),
    _w("faction","hizip / grup","n","Political faction — siyasi hizip"),
    _w("feasibility","uygulanabilirlik","n","Feasibility study — fizibilite çalışması"),
    _w("hypothetical","varsayımsal","adj","Hypothetical scenario — varsayımsal senaryo"),
    _w("inducement","teşvik","n","Financial inducement — mali teşvik"),
    _w("ingenuity","yaratıcılık","n","Creative ingenuity — yaratıcı zekâ"),
    _w("institute","kurmak","v","Institute changes — değişiklik başlatmak"),
],

"🔴 C1 İleri": [
    _w("abrupt","ani / sert","adj","Abruptly stopped — aniden durdu"),
    _w("abstain","çekimser kalmak","v","Abstention — çekimserlik"),
    _w("accentuate","vurgulamak / ön plana çıkarmak","v","Accentuated difference — belirginleşen fark"),
    _w("accolade","övgü / ödül","n","Won accolades — övgü kazandı"),
    _w("acrimony","sertlik / husumet","n","With acrimony — düşmanca"),
    _w("adamant","kararlı / inatçı","adj","Adamantly refused — kesinlikle reddetti"),
    _w("adept","uzman / çok yetenekli","adj","Adept at negotiation — müzakerede usta"),
    _w("adhere","bağlı kalmak","v","Adherence — bağlılık"),
    _w("admonish","azarlamak","v","Admonishment — azar"),
    _w("advent","gelişi / başlangıcı","n","Advent of technology — teknolojinin gelişi"),
    _w("adversity","zorluk / sıkıntı","n","Face adversity — zorluklarla yüzleş"),
    _w("affirmative","olumlu / onaylayan","adj","Affirmative action — olumlu eylem"),
    _w("aggravate","kötüleştirmek","v","Aggravated — kötüleşmiş"),
    _w("allegation","iddia / suçlama","n","False allegation — asılsız suçlama"),
    _w("alleviate","hafifletmek","v","Alleviate pain — acıyı hafiflet"),
    _w("allusion","ima / gönderme","n","Literary allusion — edebi gönderme"),
    _w("ambivalent","kararsız / çift yönlü","adj","Ambivalence — kararsızlık"),
    _w("ameliorate","iyileştirmek","v","Amelioration — iyileştirme"),
    _w("anachronism","anakronizm / zamansızlık","n","Historical anachronism — tarihsel anakronizm"),
    _w("antagonize","düşman etmek","v","Antagonism — düşmanlık"),
    _w("apathy","ilgisizlik / kayıtsızlık","n","Voter apathy — seçmen ilgisizliği"),
    _w("appease","yatıştırmak","v","Appeasement — yatıştırma"),
    _w("archaic","eski / arkaik","adj","Archaic language — eski dil"),
    _w("aspire","arzulamak","v","Aspiration — arzu"),
    _w("astute","keskin / zeki","adj","Astute observer — keskin gözlemci"),
    _w("atrophy","körelme / zayıflama","v","Muscle atrophy — kas erimesi"),
    _w("audacious","cesur / gözüpek","adj","Audacity — cesaret"),
    _w("augment","artırmak / genişletmek","v","Augmentation — artırma"),
    _w("austere","sade / tutumlu","adj","Austerity — kemer sıkma"),
    _w("authoritarian","otoriter","adj","Authoritarianism — otoriterizm"),
    _w("averse","isteksiz / karşı","adj","Risk-averse — riskten kaçınan"),
    _w("belie","yalanlamak","v","Actions belie words — eylemler sözleri yalanlar"),
    _w("belittle","küçümsemek","v","Don't belittle others — başkalarını küçümseme"),
    _w("benevolent","hayırsever","adj","Benevolence — hayırseverlik"),
    _w("benign","iyi huylu / zararsız","adj","Benign tumor — iyi huylu tümör"),
    _w("breach","ihlal etmek","v","Breach of contract — sözleşme ihlali"),
    _w("brevity","kısalık / özlülük","n","Brevity is the soul of wit — özlülük zekanın özüdür"),
    _w("candid","açık sözlü / dürüst","adj","Candor — açık sözlülük"),
    _w("catalyst","katalizör","n","Act as a catalyst — katalizör görevi gör"),
    _w("circumvent","atlatmak / dolambaçlı yoldan geçmek","v","Circumvent rules — kuralları atlatmak"),
    _w("coerce","zorlamak","v","Coercion — zorlama"),
    _w("cogent","ikna edici / mantıklı","adj","Cogent argument — güçlü argüman"),
    _w("compelling","zorlayıcı / çekici","adj","Compelling evidence — ikna edici kanıt"),
    _w("complacent","memnun / ihmalkâr","adj","Complacency — umursamazlık"),
    _w("conciliatory","uzlaşmacı","adj","Conciliation — uzlaşma"),
    _w("condescending","küçümseyici","adj","Condescension — küçümseme"),
    _w("conducive","elverişli","adj","Conducive to learning — öğrenmeye elverişli"),
    _w("convoluted","karmaşık / girift","adj","Convoluted explanation — karmaşık açıklama"),
    _w("corroborate","doğrulamak","v","Corroborating evidence — destekleyici kanıt"),
    _w("cryptic","gizemli / anlaşılmaz","adj","Cryptic message — gizemli mesaj"),
    _w("curtail","kısmak / kısıtlamak","v","Curtail spending — harcamaları kıs"),
    _w("cynical","alaycı / şüpheci","adj","Cynicism — şüphecilik"),
    _w("debilitate","zayıflatmak","v","Debilitating illness — zayıflatan hastalık"),
    _w("deferential","saygılı","adj","Deference — saygı"),
    _w("delineate","çizmek / tasvir etmek","v","Delineation — çizim / tasvir"),
    _w("demeanour","tavır / tutum","n","Professional demeanour — profesyonel tavır"),
    _w("denounce","kınamak / ihbar etmek","v","Denouncement — kınama"),
    _w("depict","resmetmek / tasvir etmek","v","Depiction — tasvir"),
    _w("deplore","kınamak / üzülmek","v","Deplorable — kınanacak"),
    _w("derivative","türev / kopya","adj","Derivative work — türev eser"),
    _w("detrimental","zararlı","adj","Detrimental effect — zararlı etki"),
    _w("deviate","sapmak","v","Deviation — sapma"),
    _w("diatribe","sert eleştiri / hücum","n","Launch a diatribe — sert eleştiri yaptı"),
    _w("dichotomy","ikiye bölünme / ikilik","n","False dichotomy — yanlış ikilik"),
    _w("diffuse","yaymak / dağıtmak","v","Diffusion — yayılma"),
    _w("diligent","çalışkan / özenli","adj","Diligence — çalışkanlık"),
    _w("discrepancy","tutarsızlık / farklılık","n","Discrepancy in data — verideki farklılık"),
    _w("dismantle","sökmek / ortadan kaldırmak","v","Dismantling — sökme"),
    _w("disparate","farklı / eşitsiz","adj","Disparity — eşitsizlik"),
    _w("disseminate","yaymak","v","Dissemination — yayma"),
    _w("dogmatic","dogmatik / katı","adj","Dogmatism — dogmatizm"),
    _w("dubious","şüpheli / kuşkulu","adj","Dubiously — şüpheyle"),
    _w("eccentric","alışılmadık / tuhaf","adj","Eccentricity — tuhaflık"),
    _w("elucidate","açıklamak","v","Elucidation — açıklama"),
    _w("eloquent","belagatli / güzel konuşan","adj","Eloquence — belağat"),
    _w("emulate","taklit etmek / örnek almak","v","Emulation — taklit"),
    _w("encompass","kapsamak","v","Encompassing — kapsayan"),
    _w("endorse","onaylamak / desteklemek","v","Endorsement — onay"),
    _w("engender","doğurmak / neden olmak","v","Engender trust — güven oluşturmak"),
    _w("entail","gerektirmek / içermek","v","This entails — bu gerektirir"),
    _w("erratic","düzensiz / tutarsız","adj","Erratic behaviour — tutarsız davranış"),
    _w("evocative","çağrıştırıcı / anlatımlı","adj","Evocative imagery — çarpıcı imgeler"),
    _w("exacerbate","ağırlaştırmak","v","Exacerbating the problem — sorunu kötüleştiriyor"),
    _w("exemplify","örnek teşkil etmek","v","Exemplification — örnekleme"),
    _w("exhaustive","kapsamlı / tüketici","adj","Exhaustive list — kapsamlı liste"),
    _w("exert","uygulamak / çaba göstermek","v","Exert pressure — baskı uygulamak"),
    _w("exploit","sömürmek","v","Exploitation — sömürü"),
    _w("extol","övmek","v","Extol virtues — erdemleri övmek"),
    _w("fallacy","yanılgı / safsata","n","Logical fallacy — mantık yanılgısı"),
    _w("fathom","anlamak / derinlik ölçmek","v","Cannot fathom why — neden olduğunu anlayamıyor"),
    _w("feasible","uygulanabilir","adj","Feasibility — uygulanabilirlik"),
    _w("fervent","ateşli / coşkulu","adj","Fervently — ateşle"),
    _w("finite","sonlu / sınırlı","adj","Finite resources — sınırlı kaynaklar"),
    _w("forestall","önlemek / önüne geçmek","v","Forestall criticism — eleştiriyi önlemek"),
    _w("fortify","güçlendirmek","v","Fortification — tahkimat"),
    _w("frugal","tutumlu","adj","Frugality — tutumluluk"),
    _w("glean","toplamak / bilgi devşirmek","v","Gleaned from data — veriden elde edilen"),
    _w("grandiose","görkemli / abartılı","adj","Grandiose plans — abartılı planlar"),
    _w("gratuitous","gereksiz / bedava","adj","Gratuitous violence — gereksiz şiddet"),
    _w("hamper","engellemek","v","Hampered by — engellenen"),
    _w("harbinger","haberci / belirtisi","n","Harbinger of change — değişimin habercisi"),
    _w("hasten","acele ettirmek","v","Hasten a process — süreci hızlandırmak"),
    _w("hinder","engel olmak","v","Hindrance — engel"),
    _w("holistic","bütünsel","adj","Holistic approach — bütünsel yaklaşım"),
    _w("hypocritical","ikiyüzlü","adj","Hypocrisy — ikiyüzlülük"),
    _w("imminent","yakın / çok yakında olan","adj","Imminent danger — yakın tehlike"),
    _w("impede","engellemek","v","Impediment — engel"),
    _w("impetus","itici güç / dürtü","n","Provide impetus — itici güç sağla"),
    _w("inadvertent","kazara / farkında olmadan","adj","Inadvertently — kazara"),
    _w("incisive","keskin / isabetli","adj","Incisive analysis — keskin analiz"),
    _w("indiscriminate","ayrım gözetmeksizin","adj","Indiscriminate use — ayrımsız kullanım"),
    _w("induce","ikna etmek / neden olmak","v","Induction — tümevarım"),
    _w("inexorable","amansız / durdurulamaz","adj","Inexorably — amansızca"),
    _w("infringe","ihlal etmek","v","Infringement — ihlal"),
    _w("ingenious","zekice / becerikli","adj","Ingenuity — yaratıcı zeka"),
    _w("instigate","kışkırtmak","v","Instigation — kışkırtma"),
    _w("intractable","inatçı / çözülmesi zor","adj","Intractable problem — çözülmesi zor sorun"),
    _w("inundate","sel basmak / bunaltmak","v","Inundated with requests — talep selinde"),
    _w("invoke","çağırmak / başvurmak","v","Invoke the law — yasaya başvurmak"),
    _w("irrefutable","çürütülemez","adj","Irrefutable evidence — çürütülemez kanıt"),
    _w("jeopardize","tehlikeye atmak","v","Jeopardized — tehlikeye atılan"),
    _w("juxtapose","yan yana koymak","v","Juxtaposition — yan yana koyma"),
    _w("languid","yorgun / ağır","adj","Languish — kölemek"),
    _w("latent","gizli / saklı","adj","Latent potential — gizli potansiyel"),
    _w("laudable","övgüye değer","adj","Laudably — övgüye değer biçimde"),
    _w("lucrative","kazançlı","adj","Lucrative deal — kazançlı anlaşma"),
    _w("malleable","şekillendirilebilir","adj","Malleable material — şekil verilebilir malzeme"),
    _w("mitigate","hafifletmek","v","Mitigating factors — hafifletici faktörler"),
    _w("mundane","sıradan / gündelik","adj","Mundane tasks — sıradan görevler"),
    _w("negate","olumsuzlamak","v","Negation — olumsuzlama"),
    _w("negligible","ihmal edilebilir / önemsiz","adj","Negligible effect — önemsiz etki"),
    _w("nuanced","nüanslı / ince ayrımlı","adj","Nuance — ince anlam farkı"),
    _w("obscure","belirsiz / gizlemek","adj","Obscurity — belirsizlik"),
    _w("obstinate","inatçı","adj","Obstinacy — inatçılık"),
    _w("ostensible","görünürde / sözde","adj","Ostensibly — görünüşte"),
    _w("ostracize","dışlamak","v","Ostracism — dışlanma"),
    _w("overarching","kapsayıcı / genel","adj","Overarching goal — kapsayıcı hedef"),
    _w("paradox","paradoks / çelişki","n","Paradoxical — paradoksal"),
    _w("peculiar","garip / kendine özgü","adj","Peculiarity — gariplik"),
    _w("perfidious","hain / sadakatsiz","adj","Perfidy — hainlik"),
    _w("perilous","tehlikeli","adj","Perilously — tehlikeli şekilde"),
    _w("pertinent","uygun / ilgili","adj","Pertinence — ilgililik"),
    _w("pessimistic","kötümser","adj","Pessimism — kötümserlik"),
    _w("pragmatic","pratik / pragmatik","adj","Pragmatism — pragmatizm"),
    _w("precarious","güvensiz / tehlikeli","adj","Precariously — güvensiz şekilde"),
    _w("precipitate","hızlandırmak / aceleci","v","Precipitation — çökelme / yağış"),
    _w("predispose","yatkın kılmak","v","Predisposition — yatkınlık"),
    _w("prevail","hâkim olmak / kazanmak","v","Prevailing — hâkim olan"),
    _w("prodigious","olağanüstü / devasa","adj","Prodigiously — olağanüstü şekilde"),
    _w("profound","derin / köklü","adj","Profoundly — derinden"),
    _w("propagate","yaymak / üretmek","v","Propaganda — propaganda"),
    _w("provocative","kışkırtıcı","adj","Provocation — kışkırtma"),
    _w("rebuke","azarlamak / kınamak","v","Received a rebuke — azar işitti"),
    _w("rectify","düzeltmek","v","Rectification — düzeltme"),
    _w("redundant","gereksiz / fazlalık","adj","Redundancy — tekrar / gereksizlik"),
    _w("refute","çürütmek","v","Refutation — çürütme"),
    _w("relentless","amansız / durmaksızın","adj","Relentlessly — amansızca"),
    _w("relinquish","bırakmak / vazgeçmek","v","Relinquishment — vazgeçiş"),
    _w("repudiate","reddetmek / inkâr etmek","v","Repudiation — ret"),
    _w("resilient","dirençli / dayanıklı","adj","Resilience — dayanıklılık"),
    _w("reticent","çekingen / ketum","adj","Reticence — ketumlik"),
    _w("rhetorical","retorik / söylemsel","adj","Rhetorically — retorik açısından"),
    _w("sanctimonious","yüksekten bakan / sahte dindar","adj","Sanctimony — sahte erdem"),
    _w("scrutinize","dikkatle incelemek","v","Scrutiny — inceleme"),
    _w("spurious","sahte / asılsız","adj","Spurious claim — asılsız iddia"),
    _w("squander","çarçur etmek","v","Squandered resources — harcanan kaynaklar"),
    _w("stagnant","durgun / hareketsiz","adj","Stagnation — durgunluk"),
    _w("steadfast","kararlı / azimli","adj","Steadfastly — kararlılıkla"),
    _w("stringent","sıkı / katı","adj","Stringent regulations — katı düzenlemeler"),
    _w("subjugate","boyun eğdirmek","v","Subjugation — boyun eğdirme"),
    _w("substantiate","kanıtlamak / desteklemek","v","Substantiation — kanıtlama"),
    _w("subtle","ince / nüanslı","adj","Subtlety — incelik"),
    _w("succinct","özlü / kısa","adj","Succinctly — özlü şekilde"),
    _w("superficial","yüzeysel","adj","Superficiality — yüzeysellik"),
    _w("surpass","geçmek / aşmak","v","Surpassing expectations — beklentileri aşmak"),
    _w("susceptible","duyarlı / yatkın","adj","Susceptibility — duyarlılık"),
    _w("tenuous","zayıf / ince","adj","Tenuous connection — zayıf bağlantı"),
    _w("trivial","önemsiz / basit","adj","Triviality — önemsizlik"),
    _w("unequivocal","kesin / net","adj","Unequivocally — tartışmasız biçimde"),
    _w("unprecedented","benzeri görülmemiş","adj","Unprecedented scale — benzeri görülmemiş ölçek"),
    _w("verbose","fazla sözcük kullanan","adj","Verbosity — gereksiz uzunluk"),
    _w("vindicate","haklı çıkarmak","v","Vindication — aklanma"),
    _w("volatile","değişken / uçucu","adj","Volatility — oynaklık"),
    _w("zealous","hevesli / gayretli","adj","Zeal — gayret, heves"),
    _w("shrewd","kurnaz / zeki","adj","Shrewdly — kurnazca"),
    _w("inherent","doğal / içkin","adj","Inherently — doğası gereği"),
    _w("pervasive","yaygın / her yere sızan","adj","Pervasiveness — yaygınlık"),
    _w("paramount","en önemli","adj","Of paramount importance — son derece önemli"),
    _w("partisan","partizan / tarafgir","adj","Partisanship — partizanlık"),
    _w("punitive","cezalandırıcı","adj","Punitive measures — cezalandırıcı tedbirler"),
    _w("revert","geri dönmek","v","Revert to old habits — eski alışkanlıklara dönmek"),
    _w("schism","bölünme / ayrılık","n","Schismatic — bölücü"),
    _w("sceptical","şüpheci","adj","Scepticism — şüphecilik"),
    _w("tenacious","inatçı / kararlı","adj","Tenacity — kararlılık"),
    _w("transgress","çiğnemek / sınırı aşmak","v","Transgression — ihlal"),
    _w("unilateral","tek taraflı","adj","Unilaterally — tek taraflı olarak"),
    _w("wield","kullanmak / sahip olmak","v","Wield power — güç kullanmak"),
    _w("abdicate","vazgeçmek","v","Abdicate responsibility — sorumluluktan kaçmak"),
    _w("aberrant","sapkın","adj","Aberrant behaviour — sapkın davranış"),
    _w("abhor","nefret etmek","v","Abhorrent — tiksindirici"),
    _w("abject","perişan","adj","Abject poverty — tam yoksulluk"),
    _w("absolve","aklamak","v","Absolve of blame — suçtan aklamak"),
    _w("acquiesce","razı olmak","v","Acquiesce silently — sessizce razı olmak"),
    _w("adroit","mahir / becerikli","adj","Adroit negotiator — becerikli müzakereci"),
    _w("affirmation","onaylama","n","Positive affirmation — olumlu onaylama"),
    _w("aloof","mesafeli / soğuk","adj","Remain aloof — mesafeli kalmak"),
    _w("amicable","dostane","adj","Amicable resolution — dostane çözüm"),
    _w("antagonism","düşmanlık","n","Political antagonism — siyasi düşmanlık"),
    _w("antiquated","eski / modası geçmiş","adj","Antiquated laws — çağdışı yasalar"),
    _w("apt","uygun","adj","Apt analogy — uygun benzetme"),
    _w("ardent","ateşli","adj","Ardent believer — ateşli inanan"),
    _w("ascertain","tespit etmek","v","Ascertain the truth — gerçeği tespit etmek"),
    _w("aspersion","iftira","n","Cast aspersions — iftira atmak"),
    _w("assertive","kendinden emin","adj","Be more assertive — daha kararlı ol"),
    _w("avarice","açgözlülük","n","Driven by avarice — açgözlülükle sürüklenmek"),
    _w("aversion","nefret / isteksizlik","n","Strong aversion — güçlü isteksizlik"),
    _w("avid","hevesli","adj","Avid supporter — hevesli destekçi"),
    _w("bewilder","şaşırtmak","v","Bewildering complexity — şaşırtıcı karmaşıklık"),
    _w("blatant","açık seçik / utanmaz","adj","Blatant hypocrisy — açık ikiyüzlülük"),
    _w("cajole","yaltaklanarak ikna etmek","v","Cajole someone — yaltaklanarak ikna etmek"),
    _w("callous","duygusuz","adj","Callous attitude — duygusuz tutum"),
    _w("censure","kınamak","v","Official censure — resmi kınama"),
    _w("chastise","azarlamak","v","Chastise publicly — alenen azarlamak"),
    _w("circumscribe","sınırlandırmak","v","Circumscribe power — yetkiyi sınırlandırmak"),
    _w("clamour","yüksek sesli talep","n","Public clamour — kamuoyunun talebi"),
    _w("clemency","merhamet","n","Show clemency — merhamet göstermek"),
    _w("coalesce","birleşmek","v","Coalesce into movement — harekete dönüşmek"),
    _w("coercion","zorlama","n","Under coercion — zorlama altında"),
    _w("cognizant","farkında","adj","Fully cognizant — tamamen farkında"),
    _w("collusion","suç ortaklığı","n","Secret collusion — gizli suç ortaklığı"),
    _w("complacency","rehavet","n","Dangerous complacency — tehlikeli rehavet"),
    _w("conspicuous","göze çarpan","adj","Conspicuous consumption — gösterişçi tüketim"),
    _w("contemptuous","küçümseyici","adj","Contemptuous look — küçümseyici bakış"),
    _w("copious","bol","adj","Copious amounts — bol miktarda"),
    _w("credulous","saf / kolay inanan","adj","Credulous public — saf halk"),
    _w("debase","değersizleştirmek","v","Debase standards — standartları düşürmek"),
    _w("debunk","çürütmek","v","Debunk the theory — teoriyi çürütmek"),
    _w("decisive","kararlı","adj","Decisive moment — belirleyici an"),
    _w("demise","çöküş","n","Premature demise — erken çöküş"),
    _w("desist","durmak","v","Cease and desist — dur ve bırak"),
    _w("despondent","umutsuz","adj","Feel despondent — umutsuz hissetmek"),
    _w("detract","azaltmak","v","Detract attention — dikkati dağıtmak"),
    _w("devoid","yoksun","adj","Devoid of content — içeriksiz"),
    _w("didactic","öğretici","adj","Didactic purpose — öğretici amaç"),
    _w("diligence","özen","n","Admirable diligence — takdire şayan özen"),
    _w("discern","ayırt etmek","v","Discern a pattern — bir örüntüyü ayırt etmek"),
    _w("disparage","aşağılamak","v","Disparaging tone — aşağılayıcı ton"),
    _w("dispassionate","tarafsız","adj","Dispassionate view — tarafsız bakış"),
    _w("dispel","dağıtmak","v","Dispel doubts — şüpheleri dağıtmak"),
    _w("dissuade","vazgeçirmek","v","Dissuade from acting — eylemden vazgeçirmek"),
    _w("divergent","ayrışan","adj","Divergent paths — ayrışan yollar"),
    _w("docile","uysal","adj","Docile population — uysal nüfus"),
    _w("elicit","ortaya çıkarmak","v","Elicit a reaction — tepki ortaya çıkarmak"),
    _w("enact","yürürlüğe koymak","v","Enact reform — reform yürürlüğe koymak"),
    _w("enmity","düşmanlık","n","Historic enmity — tarihi düşmanlık"),
    _w("envisage","tasavvur etmek","v","Envisage a solution — çözüm tasavvur etmek"),
    _w("estrange","yabancılaştırmak","v","Estranged partners — kopuk ortaklar"),
    _w("exasperate","çok kızdırmak","v","Exasperate everyone — herkesi çıldırtmak"),
    _w("expedient","elverişli","adj","Politically expedient — siyasi açıdan elverişli"),
    _w("fabricate","uydurmak","v","Fabricate a story — hikaye uydurmak"),
    _w("fastidious","titiz","adj","Fastidious about detail — ayrıntılara titiz"),
    _w("flagrant","açık seçik / utanmaz","adj","Flagrant disregard — açık seçik umursamazlık"),
    _w("foresight","öngörü","n","Remarkable foresight — olağanüstü öngörü"),
    _w("formidable","zorlu","adj","Formidable challenge — zorlu meydan okuma"),
    _w("forthright","açık sözlü","adj","Forthright answer — açık sözlü yanıt"),
    _w("fraudulent","hileli","adj","Fraudulent activity — hileli faaliyet"),
    _w("futile","boşuna","adj","Futile resistance — boşuna direniş"),
    _w("haphazard","gelişigüzel","adj","Haphazard planning — gelişigüzel planlama"),
    _w("haughty","kibirli","adj","Haughty demeanour — kibirli tavır"),
    _w("heinous","korkunç","adj","Heinous act — korkunç eylem"),
    _w("herald","haber vermek","v","Herald change — değişimi müjdelemek"),
    _w("illicit","yasadışı","adj","Illicit trade — yasadışı ticaret"),
    _w("impasse","çıkmaz","n","Diplomatic impasse — diplomatik çıkmaz"),
    _w("impartial","tarafsız","adj","Impartial assessment — tarafsız değerlendirme"),
    _w("implicate","suçlamak / dahil etmek","v","Implicate in wrongdoing — suça karıştırmak"),
    _w("incumbent","görevdeki","adj","Incumbent leader — görevdeki lider"),
    _w("indict","iddianame düzenlemek","v","Indicted for crimes — suçlardan yargılanmak"),
    _w("inept","beceriksiz","adj","Inept management — beceriksiz yönetim"),
    _w("inexplicable","açıklanamaz","adj","Inexplicable decision — açıklanamaz karar"),
    _w("infuriate","çıldırtmak","v","Infuriate supporters — destekçileri çıldırtmak"),
    _w("ingrained","köklü","adj","Ingrained bias — köklü önyargı"),

],

"🟣 C2 Üst-İleri": [
    _w("abjure","vazgeçmek / inkâr etmek","v","Abjure one's beliefs — inançlarından vazgeçmek"),
    _w("abnegate","feragat etmek","v","Abnegation — kendini feda etme"),
    _w("abrogate","feshetmek / iptal etmek","v","Abrogation of a treaty — antlaşmanın iptali"),
    _w("abscond","kaçmak / sıvışmak","v","Absconded with funds — fonlarla kaçtı"),
    _w("abstemious","perhizkâr / ölçülü","adj","Abstemious diet — ölçülü diyet"),
    _w("accrue","birikmek / tahakkuk etmek","v","Interest accrues — faiz birikir"),
    _w("acerbic","keskin / sert / iğneleyici","adj","Acerbic wit — keskin zeka"),
    _w("acumen","keskin zekâ / sezgi","n","Business acumen — iş zekası"),
    _w("adumbrate","ana hatlarıyla belirtmek","v","Adumbrated the plan — planı özetledi"),
    _w("alacrity","isteklilik / çeviklik","n","With alacrity — şevkle"),
    _w("allay","yatıştırmak / gidermek","v","Allay fears — korkuları gidermek"),
    _w("amalgamate","birleştirmek / kaynaştırmak","v","Amalgamation — birleşme"),
    _w("ambiguity","belirsizlik","n","Deliberate ambiguity — kasıtlı belirsizlik"),
    _w("anachronistic","anakronistik / zamanla bağdaşmayan","adj","Anachronistic view — çağ dışı görüş"),
    _w("animus","düşmanlık / kötü niyet","n","Personal animus — kişisel husumet"),
    _w("anomalous","anormal / alışılmadık","adj","Anomalous result — anormal sonuç"),
    _w("anomaly","anomali / sapma","n","Statistical anomaly — istatistiksel sapma"),
    _w("antithesis","karşıtlık / zıt","n","The antithesis of — tam karşıtı"),
    _w("aphorism","özdeyiş / vecize","n","Ancient aphorism — antik özdeyiş"),
    _w("apostate","din değiştiren / dönme","n","Political apostate — siyasi dönme"),
    _w("approbation","onay / takdir","n","Seek approbation — onay aramak"),
    _w("arcane","gizemli / gizli","adj","Arcane knowledge — gizli bilgi"),
    _w("arduous","güç / yorucu","adj","Arduous task — çetin görev"),
    _w("argot","argo / jargon","n","Criminal argot — suç jargonu"),
    _w("arrogate","haksız yere sahip çıkmak","v","Arrogated authority — yetkiyi gasp etmek"),
    _w("ascetic","zahit / çileci","adj","Asceticism — çilecilik"),
    _w("assuage","yatıştırmak / gidermek","v","Assuage guilt — suçluluk duygusunu gidermek"),
    _w("atavism","atavizm / geri dönüş","n","Atavistic instinct — ilkel içgüdü"),
    _w("attenuate","zayıflatmak / azaltmak","v","Attenuated signal — zayıflatılmış sinyal"),
    _w("augury","kehanet / işaret","n","Ill augury — kötü alâmet"),
    _w("aver","kesinlikle ileri sürmek","v","Averred innocence — masumiyetini kesinlikle savundu"),
    _w("banal","sıradan / klişe","adj","Banality — sıradanlık"),
    _w("bellicose","savaşçı / kavgacı","adj","Bellicose rhetoric — savaşçı söylem"),
    _w("bemoan","şikâyet etmek / ağlamak","v","Bemoaned the loss — kaybı için yas tuttu"),
    _w("bifurcate","ikiye ayrılmak","v","Bifurcation — ikiye ayrılma"),
    _w("blandishment","yaltaklanma / kandırma","n","Empty blandishments — boş pohpohlamalar"),
    _w("bode","işaret etmek","v","Bodes well — iyi habercisi"),
    _w("bombastic","abartılı / şişirilmiş","adj","Bombastic speech — şişirilmiş konuşma"),
    _w("bucolic","pastoral / kırsal","adj","Bucolic setting — pastoral ortam"),
    _w("byzantine","karmaşık / dolambaçlı","adj","Byzantine regulations — karmaşık düzenlemeler"),
    _w("cacophony","kakofoni / gürültü patırtı","n","Cacophonous — uyumsuz sesli"),
    _w("calumny","iftira / karalama","n","Spread calumny — iftira yaymak"),
    _w("canonical","standart / kanonik","adj","Canonical text — kanonik metin"),
    _w("capitulate","teslim olmak","v","Capitulation — teslim oluş"),
    _w("capricious","kaprisli / değişken","adj","Capriciousness — kaprislilik"),
    _w("castigate","şiddetle eleştirmek","v","Castigated for mistakes — hatalar için şiddetle eleştirildi"),
    _w("caveat","uyarı / çekince","n","With the caveat that — şartıyla"),
    _w("chide","azarlamak","v","Chided for carelessness — dikkatsizlik için azarlandı"),
    _w("chicanery","hile / aldatmaca","n","Legal chicanery — yasal hile"),
    _w("circumlocution","dolambaçlı anlatım","n","Avoid circumlocution — dolambaçtan kaçın"),
    _w("circumspect","temkinli / ihtiyatlı","adj","Circumspection — temkinlilik"),
    _w("clandestine","gizli / el altından yapılan","adj","Clandestine operation — gizli operasyon"),
    _w("cogitate","düşünmek / derin düşünceye dalmak","v","Cogitation — derin düşünce"),
    _w("commensurate","orantılı / uygun","adj","Commensurate with — ile orantılı"),
    _w("compunction","pişmanlık / vicdan azabı","n","Without compunction — pişmanlık duymadan"),
    _w("concomitant","eş zamanlı / birlikte gelen","adj","Concomitant effects — eş zamanlı etkiler"),
    _w("condone","göz yummak / affetmek","v","Cannot condone — göz yumamaz"),
    _w("confound","şaşırtmak / karıştırmak","v","Confounded expectations — beklentileri boşa çıkardı"),
    _w("consummate","mükemmel / eksiksiz","adj","Consummate professional — tam anlamıyla profesyonel"),
    _w("contentious","tartışmalı / kavgacı","adj","Contentious issue — tartışmalı konu"),
    _w("contrite","pişman","adj","Contrition — pişmanlık"),
    _w("convolution","karmaşıklık","n","Convoluted — karmaşık"),
    _w("corrosive","aşındırıcı / zararlı","adj","Corrosive effect — aşındırıcı etki"),
    _w("countenance","yüz ifadesi / onaylamak","n","Gave no countenance — onaylamadı"),
    _w("credulity","saflık / kolay inanma","n","Strain credulity — inanılırlığı zorlamak"),
    _w("culpable","suçlu / kabahatli","adj","Culpability — sorumluluk"),
    _w("daunt","yıldırmak / cesaretini kırmak","v","Daunting task — göz korkutucu görev"),
    _w("dearth","kıtlık / eksiklik","n","Dearth of evidence — kanıt eksikliği"),
    _w("decry","kınamak / şiddetle eleştirmek","v","Decried as unfair — adaletsiz olarak kınadı"),
    _w("deference","saygı / itaat","n","In deference to — saygıyla"),
    _w("deign","lütfetmek / tenezzül etmek","v","Deigned to reply — yanıtlamayı lütfetti"),
    _w("deleterious","zararlı","adj","Deleterious effects — zararlı etkiler"),
    _w("demur","itiraz etmek","v","Without demur — itiraz etmeden"),
    _w("denigrate","küçük düşürmek","v","Denigration — karalama"),
    _w("desultory","düzensiz / dağınık","adj","Desultory conversation — dağınık konuşma"),
    _w("diffidence","utangaçlık / çekingenlik","n","Diffident — çekingen"),
    _w("dilettante","amatör / hobi olarak uğraşan","n","Dilettantism — yüzeysel ilgi"),
    _w("disaffected","hoşnutsuz","adj","Disaffection — hoşnutsuzluk"),
    _w("disavow","inkâr etmek / reddediyorum","v","Disavowal — inkâr"),
    _w("disconcert","şaşırtmak / rahatsız etmek","v","Disconcerting — rahatsız edici"),
    _w("discourse","söylem / konuşma","n","Political discourse — siyasi söylem"),
    _w("disdain","hor görmek / küçümsemek","v","Disdainful — küçümseyici"),
    _w("dissonance","uyumsuzluk / çelişki","n","Cognitive dissonance — bilişsel çelişki"),
    _w("draconian","sert / aşırı katı","adj","Draconian measures — sert tedbirler"),
    _w("duplicity","iki yüzlülük","n","Duplicitous — iki yüzlü"),
    _w("ebullient","coşkulu / neşeli","adj","Ebullience — coşku"),
    _w("effusive","coşkulu / aşırı samimi","adj","Effusively — coşkuyla"),
    _w("egregious","apaçık / rezil","adj","Egregiously — rezilce"),
    _w("elitist","seçkinci","adj","Elitism — seçkincilik"),
    _w("embroil","karıştırmak","v","Embroiled in controversy — tartışmaya sürüklendi"),
    _w("empiricism","deneycilik / ampirizm","n","Empiricist — deneyciliği savunan"),
    _w("enervate","güçten düşürmek","v","Enervating heat — yorucu sıcak"),
    _w("ennui","sıkıntı / bıkkınlık","n","Profound ennui — derin bıkkınlık"),
    _w("ephemeral","geçici / kısa ömürlü","adj","Ephemeral trends — geçici trendler"),
    _w("equivocate","muğlak konuşmak","v","Equivocation — muğlaklık"),
    _w("erudite","bilgili / âlim","adj","Erudition — bilgelik"),
    _w("esoteric","ezoterik / gizemli","adj","Esoteric knowledge — gizemli bilgi"),
    _w("euphemism","örtmece / güzel söyleyiş","n","Euphemistic — örtmeceli"),
    _w("excoriate","şiddetle eleştirmek","v","Excoriated in the press — basında şiddetle eleştirildi"),
    _w("exculpate","aklamak","v","Exculpation — aklanma"),
    _w("execrate","lanetlemek","v","Execrated — lanetlenmiş"),
    _w("exigent","acil / zorunlu","adj","Exigent circumstances — acil koşullar"),
    _w("expiate","kefaret ödemek","v","Expiation — kefaret"),
    _w("expunge","silmek / karalamak","v","Expunged from record — kayıttan silindi"),
    _w("feckless","beceriksiz / sorumsuz","adj","Fecklessness — sorumsuzluk"),
    _w("felicitous","yerinde / uygun","adj","Felicitously — uygun şekilde"),
    _w("flout","çiğnemek / saygısızca geçmek","v","Flouted the rules — kurallara aldırmadı"),
    _w("foment","kışkırtmak / körüklemek","v","Foment discord — anlaşmazlık körüklemek"),
    _w("fractious","huysuz / kavgacı","adj","Fractious debate — gürültülü tartışma"),
    _w("fulminate","şiddetle kınamak","v","Fulminated against — şiddetle kınadı"),
    _w("garrulous","çok konuşan / geveze","adj","Garrulousness — gevezelik"),
    _w("germane","ilgili / uygun","adj","Germane to the discussion — tartışmayla ilgili"),
    _w("grandiloquent","görkemli / tumturaklı konuşan","adj","Grandiloquence — tumturak"),
    _w("gratify","memnun etmek","v","Gratifying — memnuniyet verici"),
    _w("grievous","ağır / ciddi","adj","Grievous error — ciddi hata"),
    _w("hegemony","hegemonya / üstünlük","n","Cultural hegemony — kültürel egemenlik"),
    _w("hermetic","hermetik / kapalı","adj","Hermetically sealed — hermetik kapalı"),
    _w("hubris","kibir / aşırı özgüven","n","Hubris leads to downfall — kibir düşüşe yol açar"),
    _w("hyperbole","abartma / mübalağa","n","Hyperbolic — abartılı"),
    _w("iconoclast","put kıran / alışılmışa karşı çıkan","n","Iconoclastic ideas — devrimci fikirler"),
    _w("idiosyncratic","kendine özgü","adj","Idiosyncrasy — kendine özgü özellik"),
    _w("ignominious","utanç verici / aşağılayıcı","adj","Ignominy — utanç"),
    _w("imbue","doldurmak / aşılamak","v","Imbued with meaning — anlam dolu"),
    _w("immutable","değişmez","adj","Immutability — değişmezlik"),
    _w("impecunious","parasız / yoksul","adj","Impecuniously — parasız halde"),
    _w("imperious","buyurgan / zorba","adj","Imperiously — buyurganca"),
    _w("imperturbable","sakin / soğukkanlı","adj","Imperturbability — soğukkanlılık"),
    _w("implacable","amansız / barışmaz","adj","Implacably — amansızca"),
    _w("impugn","sorgulamak / itiraz etmek","v","Impugned his integrity — dürüstlüğünü sorguladı"),
    _w("incendiary","ateşlendirici / kışkırtıcı","adj","Incendiary speech — kışkırtıcı konuşma"),
    _w("inchoate","henüz gelişmemiş","adj","Inchoate ideas — ham fikirler"),
    _w("inimical","zararlı / düşmanca","adj","Inimical to progress — ilerlemeye zararlı"),
    _w("insidious","sinsi / fark ettirmeden zararlı","adj","Insidiously — sinsi biçimde"),
    _w("insolent","küstah","adj","Insolence — küstahlık"),
    _w("intemperate","aşırı / ölçüsüz","adj","Intemperance — ölçüsüzlük"),
    _w("internecine","karşılıklı yıkıcı","adj","Internecine conflict — iç çatışma"),
    _w("intransigent","uzlaşmaz","adj","Intransigence — uzlaşmazlık"),
    _w("inveterate","köklü / eski alışkanlığı olan","adj","Inveterate habit — köklü alışkanlık"),
    _w("irascible","çabuk kızan / sinirli","adj","Irascibility — sinirlilik"),
    _w("laconic","az sözlü / özlü","adj","Laconically — kısaca"),
    _w("lassitude","yorgunluk / halsizlik","n","Mental lassitude — zihinsel yorgunluk"),
    _w("loquacious","geveze","adj","Loquacity — gevezelik"),
    _w("lucid","açık / anlaşılır","adj","Lucidity — açıklık"),
    _w("magnanimous","büyük ruhlu / cömert","adj","Magnanimity — cömertlik"),
    _w("malevolent","kötü niyetli","adj","Malevolence — kötü niyet"),
    _w("malfeasance","kötüye kullanım / yolsuzluk","n","Official malfeasance — resmî yolsuzluk"),
    _w("mendacious","yalancı","adj","Mendacity — yalancılık"),
    _w("mercurial","değişken / canlı","adj","Mercurial temperament — değişken mizaç"),
    _w("metaphysical","metafizik","adj","Metaphysics — metafizik"),
    _w("meticulous","titiz","adj","Meticulously — titizlikle"),
    _w("misanthropic","insandan nefret eden","adj","Misanthropy — insanlık düşmanlığı"),
    _w("mollify","yatıştırmak","v","Mollified the angry crowd — öfkeli kalabalığı yatıştırdı"),
    _w("moribund","ölmekte olan / çökmekte","adj","A moribund industry — çöküşte bir sektör"),
    _w("mordant","iğneleyici / sert","adj","Mordant humour — keskin mizah"),
    _w("nebulous","belirsiz / bulanık","adj","Nebulous concept — belirsiz kavram"),
    _w("nefarious","kötü niyetli / alçak","adj","Nefarious scheme — alçakça plan"),
    _w("nihilistic","nihilist / hiççi","adj","Nihilism — nihilizm"),
    _w("obdurate","inatçı / duyarsız","adj","Obduracy — duyarsızlık"),
    _w("obfuscate","kasıtlı karıştırmak","v","Obfuscation — karartma"),
    _w("oblique","dolaylı / eğri","adj","Obliquely — dolaylı olarak"),
    _w("obsequious","dalkavuk / yüze gülücü","adj","Obsequiously — dalkavukça"),
    _w("odious","iğrenç / tiksindirici","adj","Odiously — iğrenç biçimde"),
    _w("omniscient","her şeyi bilen","adj","Omniscience — her şeyi bilme"),
    _w("opprobrium","alenen utanç / kınama","n","Public opprobrium — kamuoyu kınaması"),
    _w("ostensibly","görünüşte","adv","Ostensibly neutral — görünüşte tarafsız"),
    _w("panacea","her derde deva","n","No panacea — kolay çözüm yok"),
    _w("parochial","dar görüşlü / yerel","adj","Parochialism — dar görüşlülük"),
    _w("parsimony","cimrilik","n","Parsimonious — cimri"),
    _w("pejorative","aşağılayıcı","adj","Pejorative term — aşağılayıcı terim"),
    _w("pellucid","açık / şeffaf","adj","Pellucid prose — berrak nesir"),
    _w("penurious","yoksul / cimri","adj","Penury — yoksulluk"),
    _w("perfunctory","şeklen yapılan / üstünkörü","adj","Perfunctorily — üstünkörü biçimde"),
    _w("perspicacious","zeki / anlayışlı","adj","Perspicacity — zekâ"),
    _w("petulant","huysuz / titiz","adj","Petulance — huysuzluk"),
    _w("philistine","sanattan anlamayan / kaba","n","Philistinism — kültürsüzlük"),
    _w("placate","yatıştırmak","v","Placated the protesters — protestocuları yatıştırdı"),
    _w("platitude","basmakalıp söz","n","Platitudinous — klişe"),
    _w("plenary","tam / tam yetkili","adj","Plenary session — genel kurul"),
    _w("polemical","tartışmalı / polemik","adj","Polemicist — polemikçi"),
    _w("pontificate","vaaz vermek / büyüklük taslamak","v","Stop pontificating — büyüklük taslamayı bırak"),
    _w("portentous","uğursuz / abartılı","adj","Portentously — kehanetle"),
    _w("posterity","gelecek nesiller","n","For posterity — gelecek nesiller için"),
    _w("presuppose","önceden varsaymak","v","Presupposition — ön varsayım"),
    _w("prevaricate","kaçamaklı konuşmak","v","Prevarication — kaçamaklı konuşma"),
    _w("probity","dürüstlük / doğruluk","n","Personal probity — kişisel dürüstlük"),
    _w("prolix","gereksiz uzun / söz cambazı","adj","Prolixity — gereksiz uzunluk"),
    _w("proscribe","yasaklamak","v","Proscription — yasaklama"),
    _w("protracted","uzayan / uzatılmış","adj","Protracted negotiations — uzun soluklu müzakereler"),
    _w("querulous","mızmız / şikayetçi","adj","Querulously — mızmızca"),
    _w("quiescent","durgun / sakin","adj","Quiescence — durgunluk"),
    _w("ramification","sonuç / dal","n","Far-reaching ramifications — geniş çaplı sonuçlar"),
    _w("rancorous","kinci / düşmanca","adj","Rancour — kin"),
    _w("ratiocinate","mantıklı düşünmek","v","Ratiocination — akıl yürütme"),
    _w("raucous","sert / gürültülü","adj","Raucously — gürültülü biçimde"),
    _w("recalcitrant","söz dinlemez / isyankâr","adj","Recalcitrance — inatçılık"),
    _w("recondite","anlaşılması güç / derin","adj","Recondite knowledge — derin bilgi"),
    _w("redoubtable","saygı duyulan / korkutucu","adj","A redoubtable opponent — zorlu bir rakip"),
    _w("refractory","inatçı / tedaviye dirençli","adj","Refractory patient — dirençli hasta"),
    _w("remonstrate","itiraz etmek / karşı çıkmak","v","Remonstrated with management — yönetimle tartıştı"),
    _w("reprehensible","kınanabilir","adj","Reprehensibly — kınanacak biçimde"),
    _w("ribald","açık saçık / müstehcen","adj","Ribaldry — açık saçıklık"),
    _w("sagacious","bilge / zeki","adj","Sagacity — bilgelik"),
    _w("salient","belirgin / önemli","adj","Salient points — önemli noktalar"),
    _w("sanguine","iyimser / kanlı","adj","Sanguinely — iyimserlikle"),
    _w("sardonic","alaycı / iğneleyici","adj","Sardonically — alaycı biçimde"),
    _w("scintillating","parlak / büyüleyici","adj","Scintillating performance — büyüleyici performans"),
    _w("sycophant","dalkavuk","n","Sycophancy — dalkavukluk"),
    _w("tacit","zımni / açıkça belirtilmemiş","adj","Tacitly — zımnen"),
    _w("temerity","arsızlık / pervasızlık","n","Had the temerity — arsızlığını gösterdi"),
    _w("tendentious","eğilimli / belirli bir amaçla yazılmış","adj","Tendentiously — kasıtlı biçimde"),
    _w("timorous","ürkek / çekingen","adj","Timorously — ürkekçe"),
    _w("torpid","uyuşuk / ağır","adj","Torpor — uyuşukluk"),
    _w("truculent","saldırgan / kavgacı","adj","Truculently — saldırganca"),
    _w("tumultuous","çalkantılı / hareketli","adj","Tumult — kargaşa"),
    _w("turpitude","ahlaksızlık","n","Moral turpitude — ahlaki yozlaşma"),
    _w("ubiquitous","her yerde bulunan","adj","Ubiquity — her yerde olma"),
    _w("unctuous","yağcı / samimi görünmeyen","adj","Unctuousness — yağcılık"),
    _w("unwitting","farkında olmadan","adj","Unwittingly — bilmeden"),
    _w("vacillate","kararsız kalmak","v","Vacillation — kararsızlık"),
    _w("vapid","içeriksiz / anlamsız","adj","Vapidly — anlamsız biçimde"),
    _w("venal","rüşvete açık","adj","Venality — rüşvetçilik"),
    _w("veracious","dürüst / doğru sözlü","adj","Veracity — doğruluk"),
    _w("vexatious","sinir bozucu","adj","Vexation — sinirlenme"),
    _w("vicarious","dolaylı / başkası adına yaşanan","adj","Vicariously — dolaylı yoldan"),
    _w("vilify","karalamak / iftira atmak","v","Vilification — karalama"),
    _w("vitriolic","aşındırıcı / keskin","adj","Vitriolic attack — yakıcı saldırı"),
    _w("vituperate","aşağılamak / sövmek","v","Vituperation — sövme"),
    _w("vouchsafe","lütfetmek / vermek","v","Vouchsafed an answer — yanıtlamayı lütfetti"),
    _w("wanton","kasıtsız / kötü niyetli","adj","Wanton destruction — kasıtsız yıkım"),
    _w("waspish","huysuz / sert","adj","Waspishly — huysuzca"),
    _w("whimsical","tuhaf / düşsel","adj","Whimsy — tuhaflık"),
    _w("wily","kurnaz / hilekâr","adj","Wiliness — kurnazlık"),
    _w("winsome","sevimli / çekici","adj","Winsomely — çekici biçimde"),
    _w("zealotry","taassup / aşırı tutuculuk","n","Religious zealotry — dini taassup"),
]

}; // YDT_STARTER_PACK sonu

// DEFAULT_VOCAB olarak Starter Pack kullanılır
const DEFAULT_VOCAB = YDT_STARTER_PACK;

// ── Yerel allData içindeki eski/sistem listelerini temizle ──
function _purgeLocalLegacyLists(dataObj) {
    if (!dataObj || typeof dataObj !== 'object') return;

    const VALID_STARTER_LISTS = new Set([
        '🟢 A2 Temel', '🔵 B1 Orta', '🟡 B2 Orta-İleri', '🔴 C1 İleri', '🟣 C2 Üst-İleri'
    ]);

    const LEGACY_EXACT = new Set([
        'Genel Kelimeler', 'Örnek Liste', 'kidsPlayer', 'paragrafSorular',
        'aiArsiv', 'Mart V2', 'Mart V1', 'Şubat V2', 'Şubat V1',
        'Liste 1', 'Liste 2', 'Liste 3', 'Liste 4', 'Liste 5',
        'YDT A1', 'YDT A2', 'YDT B1', 'YDT B2', 'YDT C1',
        'A2 Temel', 'B1 Orta', 'B2 Orta-İleri', 'C1 İleri',
    ]);

    Object.keys(dataObj).forEach(key => {
        if (VALID_STARTER_LISTS.has(key)) return; // güvenli — dokunma
        const isLegacy = LEGACY_EXACT.has(key) || /^Liste\s+\d+/.test(key);
        if (isLegacy) {
            delete dataObj[key];
        }
    });
}

function loadUserScopedData() {
    const uid = window._currentUser?.uid || 'guest';

    const rawAD = localStorage.getItem(`ydt_${uid}_all_data`);
    const rawST = localStorage.getItem(`ydt_${uid}_stats`);

    let userData = null;
    if (rawAD) { try { userData = JSON.parse(rawAD); } catch(e) { console.warn('[YDT] userData parse hatası:', e.message); } }

    if (userData && Object.keys(userData).length > 0) {
        // Kullanıcı verisi var — Starter Pack listeleri yoksa ekle
        // Kullanıcının kendi listelerini koru, starter pack listelerini ekle (overwrite etme)
        const starterKeys = Object.keys(DEFAULT_VOCAB);
        const merged = {};

        // Önce kullanıcı verisi (kendi listeleri dahil)
        Object.keys(userData).forEach(k => { merged[k] = userData[k]; });

        // Eski/sistem listelerini temizle
        _purgeLocalLegacyLists(merged);

        // Starter pack listelerinden SADECE kullanıcıda olmayanları ekle
        starterKeys.forEach(k => {
            if (!merged[k]) merged[k] = DEFAULT_VOCAB[k];
        });

        allData = merged;
    } else {
        // Yeni kullanıcı / guest — eski veriyi kontrol et
        const legacyRaw = localStorage.getItem('ydt_all_data');
        let legacyData  = null;
        if (legacyRaw) { try { legacyData = JSON.parse(legacyRaw); } catch(e) { console.warn('[YDT] legacy parse hatası:', e.message); } }

        if (legacyData && Object.keys(legacyData).length > 0) {
            // Eski formattan taşı + Starter Pack ekle
            const merged = { ...DEFAULT_VOCAB };
            Object.keys(legacyData).forEach(k => { merged[k] = legacyData[k]; });
            allData = merged;
            // Yeni anahtara yaz
            try { localStorage.setItem(`ydt_${uid}_all_data`, JSON.stringify(allData)); } catch(e) {}
        } else {
            allData = { ...DEFAULT_VOCAB };
        }
    }

    // ── Starter Pack listelerini KULLANICININ allData'sına yaz (eksik olanları)
    // Böylece yeni eklenen listeler giriş yapan kullanıcılara da görünür
    const currentKeys = Object.keys(allData);
    Object.keys(DEFAULT_VOCAB).forEach(k => {
        if (!currentKeys.includes(k)) {
            allData[k] = DEFAULT_VOCAB[k];
        }
    });

    // Stats yükle
    if (rawST) { try { Object.assign(stats, JSON.parse(rawST)); } catch(e) { console.warn('[YDT] stats parse hatası:', e.message); } }

    window.allData = allData;
    window.stats   = stats;

    if (typeof updateSelectors  === 'function') updateSelectors();
    if (typeof updateIndexStats === 'function') updateIndexStats();
}

// ── Starter Pack'ı sadece guest kullanıcı için hemen yükle
// Giriş yapan kullanıcılar için onAuthStateChanged → _loadUserData() üstleniyor
const _uid = window._currentUser?.uid || 'guest';
if (_uid === 'guest') {
    loadUserScopedData();
} else {
    // Giriş yapılmış ama allData henüz boşsa Starter Pack'ı geçici yükle
    if (!allData || Object.keys(allData).length === 0) {
        allData = { ...DEFAULT_VOCAB };
        window.allData = allData;
    }
}
