// ════════════════════════════════════════════════════
// kelimeler.js  –  Veri & stats başlatma  v4
//                  user-scoped + guest merge
//                  YDT Starter Pack (500 kelime, 4 seviye)
// ════════════════════════════════════════════════════

function getUserKey(key) {
    const uid = window._currentUser?.uid || 'guest';
    return `ydt_${uid}_${key}`;
}

let allData = {};
let stats   = {};

// Kelime nesnesi üretici — tekrar yazmayı önler
function _w(eng, tr, pos, mnemonic) {
    return { eng, tr, pos, mnemonic: mnemonic || '', story: '', errorCount: 0, correctStreak: 0, sm2_ef: 2.5, sm2_interval: 0, sm2_next: null };
}

// ════════════════════════════════════════════════════
// YDT STARTER PACK — 500 kelime, 4 seviye
// ════════════════════════════════════════════════════
const YDT_STARTER_PACK = {

"🟢 A2 Temel": [
    _w("ability","yetenek / beceri","n","A harfi gibi açık — yeteneğin kapısı"),
    _w("achieve","başarmak / elde etmek","v","A+chieve: çaba ile hedefe ulaş"),
    _w("affect","etkilemek","v","Afet gibi etkiler her şeyi"),
    _w("allow","izin vermek","v","Al + ow: al işte izni"),
    _w("amount","miktar / tutar","n","A mount: dağ kadar miktar"),
    _w("ancient","antik / çok eski","adj","Annem yaşlı ama ancient daha da yaşlı"),
    _w("anxious","endişeli / kaygılı","adj","Anksiete — kaygı kelimesinin kökü"),
    _w("approach","yaklaşmak / yaklaşım","v","Proach: yakına gelmek"),
    _w("area","alan / bölge","n","Arena gibi — geniş alan"),
    _w("argue","tartışmak","v","Arg! — sinirli ses çıkararak tartışmak"),
    _w("arrange","düzenlemek","v","Aran+ge: aranıyor düzen"),
    _w("avoid","kaçınmak","v","Void = boşluk, boşluktan kaçınmak"),
    _w("aware","farkında","adj","A-ware: dikkatli ol, farkında ol"),
    _w("awful","korkunç / berbat","adj","Awe=hayranlık ama awful=korku"),
    _w("belong","ait olmak","v","Be+long: uzun süre orada olmak"),
    _w("benefit","fayda / yarar","n","Bene = iyi (Latince): iyi şey"),
    _w("blame","suçlamak","v","B+lame: topal bırakacak kadar suçlamak"),
    _w("brave","cesur","adj","Bravissimo! — cesur alkışlar"),
    _w("broad","geniş / kapsamlı","adj","Broad Street: geniş cadde"),
    _w("calm","sakin / sakinleştirmek","adj","Calm = dalga yok, sessizlik"),
    _w("capable","yapabilir / yetenekli","adj","Cape gibi süper güç — yapabilir"),
    _w("carry","taşımak","v","Carry the load: yükü taşı"),
    _w("cause","neden olmak / sebep","v","Koz = neden"),
    _w("certain","kesin / emin","adj","Certain = sertifika gibi kesin"),
    _w("chance","şans / fırsat","n","Chance: dans etme fırsatı"),
    _w("change","değişmek / değişim","v","Change = döviz bozdurmak gibi"),
    _w("charge","ücret / şarj etmek","n","Telefonu şarj et = charge"),
    _w("choice","seçim / tercih","n","Choir = koro seçimi gibi"),
    _w("claim","iddia etmek / talep","v","Klem = sıkıştır/talep et"),
    _w("clear","açık / net","adj","Clear sky: bulutsuz net gökyüzü"),
    _w("climb","tırmanmak","v","Klim = tırmanma duvarı"),
    _w("collect","toplamak","v","Koleksiyon = toplanmış şeyler"),
    _w("combine","birleştirmek","v","Com+bine: birbirine bağlamak"),
    _w("common","yaygın / ortak","adj","Common sense: ortak akıl"),
    _w("complete","tamamlamak / tam","v","Komplet = eksiksiz tam"),
    _w("concern","endişe / ilgilendirmek","n","Konu seni ilgilendiriyor"),
    _w("condition","koşul / durum","n","Kondisyon = fiziksel durum"),
    _w("connect","bağlamak","v","Konnekt: birbirine tak"),
    _w("consider","düşünmek / değerlendirmek","v","Consider = ciddi düşünmek"),
    _w("contain","içermek / kapsamak","v","Konteyner içerir her şeyi"),
    _w("continue","devam etmek","v","Kontinü = sürekli gitmek"),
    _w("control","kontrol etmek","v","Kontrol = yönetmek"),
    _w("correct","doğru / düzeltmek","adj","Korekt = hatasız"),
    _w("create","yaratmak / oluşturmak","v","Kreatif = yaratıcı"),
    _w("curious","meraklı","adj","Curiosity: merak kedinin canına mal olur"),
    _w("damage","hasar / zarar vermek","n","Damage = kırıp dökmek"),
    _w("danger","tehlike","n","Danger zone: tehlikeli bölge"),
    _w("decide","karar vermek","v","De+cide: keserek karar ver"),
    _w("delay","gecikme / ertelemek","n","Delay: geç kaldın!"),
    _w("deliver","teslim etmek","v","Delivery: kapıya teslim"),
    _w("demand","talep / istemek","n","Demand = buyur iste"),
    _w("deny","reddetmek / inkâr","v","De+ny: hayır demek"),
    _w("depend","bağlı olmak / güvenmek","v","Depend on: birine asılmak"),
    _w("describe","tanımlamak / betimlemek","v","Describe = yazarak anlatmak"),
    _w("develop","geliştirmek","v","Development: büyüme süreci"),
    _w("difficult","zor / güç","adj","Difficulty = zorluk"),
    _w("discover","keşfetmek","v","Dis+cover: örtüyü kaldır, bul"),
    _w("discuss","tartışmak / görüşmek","v","Diskus gibi döndür fikri"),
    _w("distant","uzak","adj","Distance = uzaklık"),
    _w("divide","bölmek / ayırmak","v","Divide et güçten düşür"),
    _w("doubt","şüphe / kuşku","n","Kalbi çift atan şüphe"),
    _w("drop","düşürmek / bırakmak","v","Drip-drop: damlayıp düşmek"),
    _w("earn","kazanmak","v","Earn money: para kazan"),
    _w("effort","çaba / emek","n","Effort = alın teri"),
    _w("enable","mümkün kılmak","v","En+able: yetkin hale getir"),
    _w("encourage","teşvik etmek","v","En+courage: cesaret ver"),
    _w("enjoy","zevk almak","v","Enjoy = keyif çıkar"),
    _w("entire","bütün / tüm","adj","Entire = entegre bütün"),
    _w("equal","eşit","adj","Equation: eşitlik denklemi"),
    _w("escape","kaçmak","v","Escape Room: kaçış odası"),
    _w("evidence","kanıt / delil","n","Evidence = sahneye konan kanıt"),
    _w("exact","tam / kesin","adj","Exact copy: birebir kopya"),
    _w("except","... hariç / dışında","prep","Exception = istisna"),
    _w("expect","beklemek / ummak","v","Expectation: beklenti"),
    _w("experience","deneyim / yaşamak","n","Experiens = deney yaşamak"),
    _w("explain","açıklamak","v","Explain = düzlüğe çıkar"),
    _w("fact","gerçek / olgu","n","Fact check: gerçeği denetle"),
    _w("fail","başarısız olmak","v","Fail = düşmek ama kalkacaksın"),
    _w("fair","adil / fuar","adj","Fair play: adil oyun"),
    _w("familiar","tanıdık / aşina","adj","Family = aşina olduğun insanlar"),
    _w("famous","ünlü / meşhur","adj","Fame = şöhret"),
    _w("fear","korku / korkmak","n","Fear Factor: korku programı"),
    _w("final","son / nihai","adj","Final = bitiş noktası"),
    _w("firm","sağlam / firma / kararlı","adj","Firm handshake: güçlü el sıkışma"),
    _w("focus","odaklanmak","v","Focus = mercek gibi yoğunlaş"),
    _w("follow","takip etmek","v","Follow me: beni takip et"),
    _w("force","güç / zorlamak","n","Force majeure: büyük güç"),
    _w("forget","unutmak","v","For+get: almayı unut"),
    _w("fresh","taze / yeni","adj","Fresh start: temiz başlangıç"),
    _w("friendly","arkadaşça / cana yakın","adj","Friend+ly: dostça"),
    _w("gain","kazanmak / edinmek","v","Gain = elde etmek"),
    _w("gather","toplamak / bir araya gelmek","v","Gathering: buluşma"),
    _w("general","genel","adj","General knowledge: genel bilgi"),
    _w("gentle","nazik / yumuşak","adj","Gentleman: nazik adam"),
    _w("goal","hedef / gol","n","Goal = gol atmak gibi hedefe ulaşmak"),
    _w("grand","büyük / görkemli","adj","Grand Canyon: görkemli kanyon"),
    _w("grateful","minnettar","adj","Grate+ful: iyiliğe dolu"),
    _w("grow","büyümek / gelişmek","v","Grow up: büyü"),
    _w("guard","korumak / gardiyan","v","Guard = kalkan tutan"),
    _w("guess","tahmin etmek","v","Guess who: kim bu?"),
    _w("happen","olmak / gerçekleşmek","v","What happened? Ne oldu?"),
    _w("harm","zarar vermek / zarar","v","Harm = kötülük etmek"),
    _w("honest","dürüst","adj","Honest Abe: dürüst Lincoln"),
    _w("huge","devasa / çok büyük","adj","Huge = Hulk gibi büyük"),
    _w("hurt","acı vermek / yaralamak","v","Hurt = yürek acısı"),
    _w("ignore","görmezden gelmek","v","Ignore = yok say"),
    _w("imagine","hayal etmek","v","Imagination = hayal gücü"),
    _w("improve","geliştirmek / iyileştirmek","v","Improve = daha iyi yap"),
    _w("include","dahil etmek / içermek","v","Inclusive: kapsayıcı"),
    _w("increase","artırmak / artış","v","Increase = büyüt"),
    _w("indicate","göstermek / belirtmek","v","Indicator: gösterge"),
    _w("influence","etki / etkilemek","n","Influencer = etkileyici"),
    _w("injure","yaralamak","v","Injury time: uzatma süresi"),
    _w("insist","ısrar etmek","v","Israr = insist"),
    _w("intend","niyet etmek","v","Intention: niyet"),
    _w("interest","ilgi / faiz","n","Interest rate: faiz oranı"),
    _w("introduce","tanıtmak","v","Introduction: giriş"),
    _w("invent","icat etmek","v","Inventor: mucit"),
    _w("invite","davet etmek","v","Invitation: davetiye"),
    _w("join","katılmak / birleşmek","v","Join the party: partiye katıl"),
    _w("judge","yargılamak / hakim","v","Judge = adalet terazisi"),
    _w("keep","tutmak / saklamak","v","Keep it: sakla"),
    _w("lack","eksikliği olmak / yokluk","v","Lack = boşluk var"),
    _w("laugh","gülmek","v","Laugh out loud: LOL"),
    _w("lead","önderlik etmek / lider","v","Leader = öncü"),
    _w("learn","öğrenmek","v","Learn = beyne kaydet"),
    _w("leave","ayrılmak / bırakmak","v","Leave a note: not bırak")
],

"🔵 B1 Orta": [
    _w("abandon","terk etmek","v","Abandon ship: gemiyi terk et"),
    _w("abstract","soyut / özet","adj","Abstract art: soyut sanat"),
    _w("abundant","bol / bereketli","adj","Abundant harvest: bol hasat"),
    _w("accurate","doğru / isabetli","adj","Accurate aim: isabetli nişan"),
    _w("acknowledge","kabul etmek / tanımak","v","Acknowledge = teslim almak"),
    _w("acquire","edinmek / kazanmak","v","Acquire skills: beceri kazan"),
    _w("adapt","uyum sağlamak","v","Adapt or die: uyum sağla ya da yok ol"),
    _w("adequate","yeterli","adj","Adequate prep = yeterli hazırlık"),
    _w("admire","hayran olmak","v","Admire = takdirle bakmak"),
    _w("adopt","benimsemek / evlat edinmek","v","Adopt a policy: politika benimse"),
    _w("advance","ilerlemek / gelişme","v","Advanced level: ileri seviye"),
    _w("advantage","avantaj / üstünlük","n","Take advantage: avantaj kullan"),
    _w("advertise","reklam yapmak","v","Advertisement: reklam"),
    _w("advise","tavsiye etmek","v","Adviser: danışman"),
    _w("aggressive","saldırgan","adj","Aggressive dog: saldırgan köpek"),
    _w("aid","yardım etmek / yardım","v","First aid: ilk yardım"),
    _w("alert","uyarmak / tetikte","v","Alert system: uyarı sistemi"),
    _w("allocate","tahsis etmek","v","Allocate budget: bütçe ayır"),
    _w("alter","değiştirmek / değişmek","v","Alteration: değişiklik"),
    _w("amaze","şaşırtmak","v","Amazing = şaşırtıcı"),
    _w("ambition","hırs / tutku","n","Ambitious = hırslı"),
    _w("analyse","analiz etmek","v","Analysis: çözümleme"),
    _w("anxiety","kaygı / endişe","n","Anxiety attack: panik atağı"),
    _w("apparent","açık / belirgin / görünür","adj","Apparently: görünüşe göre"),
    _w("apply","başvurmak / uygulamak","v","Apply for a job: iş başvurusu"),
    _w("appropriate","uygun / yerinde","adj","Appropriate dress: uygun kıyafet"),
    _w("approve","onaylamak","v","Approval: onay"),
    _w("assess","değerlendirmek","v","Assessment: değerlendirme"),
    _w("assign","atamak / görevlendirmek","v","Assignment: ödev"),
    _w("assist","yardım etmek","v","Assistant: yardımcı"),
    _w("assume","varsaymak / üstlenmek","v","Assumption: varsayım"),
    _w("attach","eklemek / bağlamak","v","Attachment: ek dosya"),
    _w("attempt","denemek / girişim","v","Attempt = deneme atışı"),
    _w("attend","katılmak / gitmek","v","Attend class: derse katıl"),
    _w("attitude","tutum / davranış","n","Attitude problem: tutum sorunu"),
    _w("authentic","özgün / gerçek","adj","Authentic taste: özgün lezzet"),
    _w("available","mevcut / uygun","adj","Available now: şu an mevcut"),
    _w("average","ortalama","n","Average score: ortalama puan"),
    _w("barrier","engel / bariyer","n","Language barrier: dil engeli"),
    _w("behave","davranmak","v","Behaviour: davranış"),
    _w("bias","önyargı / eğilim","n","Biased opinion: önyargılı görüş"),
    _w("boost","artırmak / güçlendirmek","v","Boost confidence: özgüveni artır"),
    _w("burden","yük / ağır sorumluluk","n","Burden of proof: ispat yükü"),
    _w("challenge","meydan okumak / zorluk","n","Challenge accepted: kabul ettim"),
    _w("circumstance","koşul / durum","n","Under circumstances: koşullar altında"),
    _w("colleague","meslektaş / iş arkadaşı","n","Colleagues = takım arkadaşları"),
    _w("commit","adamak / işlemek","v","Commit to a goal: hedefe adanmak"),
    _w("communicate","iletişim kurmak","v","Communication: iletişim"),
    _w("compare","karşılaştırmak","v","Compare prices: fiyat karşılaştır"),
    _w("compete","rekabet etmek","v","Competition: yarışma"),
    _w("complex","karmaşık / kompleks","adj","Complex system: karmaşık sistem"),
    _w("concentrate","yoğunlaşmak","v","Concentration: konsantrasyon"),
    _w("conclude","sonuçlandırmak","v","Conclusion: sonuç"),
    _w("conflict","çatışma / çelişki","n","Conflict of interest: çıkar çatışması"),
    _w("confuse","şaşırtmak / karıştırmak","v","Confusion: karışıklık"),
    _w("consequence","sonuç / etki","n","Consequence of actions: eylemlerin sonucu"),
    _w("consistent","tutarlı","adj","Consistent effort: tutarlı çaba"),
    _w("contrast","zıtlık / karşıtlık","n","In contrast: zıt olarak"),
    _w("convince","ikna etmek","v","Convincing argument: ikna edici"),
    _w("cope","başa çıkmak","v","Cope with stress: stresle başa çık"),
    _w("crisis","kriz","n","Crisis management: kriz yönetimi"),
    _w("criticise","eleştirmek","v","Criticism: eleştiri"),
    _w("crucial","çok önemli / kritik","adj","Crucial moment: kritik an"),
    _w("debt","borç","n","Debt crisis: borç krizi"),
    _w("decline","azalmak / reddetmek","v","Decline an offer: teklifi reddet"),
    _w("dedicate","adamak / ithaf etmek","v","Dedicated teacher: adanmış öğretmen"),
    _w("define","tanımlamak","v","Definition: tanım"),
    _w("demonstrate","göstermek / kanıtlamak","v","Demonstration: gösteri"),
    _w("detect","tespit etmek / saptamak","v","Detector: dedektör"),
    _w("devote","adamak / tahsis etmek","v","Devoted fan: adanmış hayran"),
    _w("distinct","belirgin / farklı","adj","Distinct smell: belirgin koku"),
    _w("distribute","dağıtmak","v","Distribution: dağıtım"),
    _w("dominate","hâkim olmak / egemen","v","Dominate the market: pazara hakim"),
    _w("dramatic","dramatik / çarpıcı","adj","Dramatic change: çarpıcı değişim"),
    _w("efficient","verimli / etkin","adj","Efficient system: verimli sistem"),
    _w("eliminate","ortadan kaldırmak","v","Eliminate waste: israfı gider"),
    _w("emerge","ortaya çıkmak","v","Emerging market: gelişen pazar"),
    _w("emphasise","vurgulamak","v","Emphasis: vurgu"),
    _w("employ","işe almak","v","Employee: çalışan"),
    _w("ensure","sağlamak / garanti etmek","v","Ensure safety: güvenliği sağla"),
    _w("establish","kurmak / oluşturmak","v","Establish trust: güven kur"),
    _w("evaluate","değerlendirmek","v","Evaluation: değerlendirme"),
    _w("exceed","aşmak / geçmek","v","Exceed expectations: beklentileri aş"),
    _w("exclude","dışlamak / hariç tutmak","v","Exclusive club: özel kulüp"),
    _w("expand","genişlemek / büyümek","v","Expansion: genişleme"),
    _w("expose","maruz bırakmak / ifşa","v","Exposure: maruz kalma"),
    _w("extend","uzatmak / genişletmek","v","Extension: uzantı"),
    _w("extreme","aşırı / uç","adj","Extreme sport: aşırı spor"),
    _w("facilitate","kolaylaştırmak","v","Facilitator: kolaylaştırıcı"),
    _w("factor","etken / faktör","n","Risk factor: risk etkeni"),
    _w("flexible","esnek","adj","Flexible schedule: esnek program"),
    _w("fluent","akıcı","adj","Fluent English: akıcı İngilizce"),
    _w("found","kurmak (örgüt)","v","Founded in 1920: 1920'de kuruldu"),
    _w("frequently","sık sık","adv","Frequent flyer: sık uçan"),
    _w("fund","fon / finanse etmek","n","Funding: finansman"),
    _w("generate","üretmek / oluşturmak","v","Generate income: gelir üret"),
    _w("global","küresel","adj","Global warming: küresel ısınma"),
    _w("gradual","kademeli / aşamalı","adj","Gradual change: aşamalı değişim"),
    _w("guarantee","garanti etmek","v","Guarantee = kesin söz"),
    _w("illustrate","örneklemek / göstermek","v","Illustration: illüstrasyon"),
    _w("impact","etki / çarpmak","n","High impact: yüksek etki"),
    _w("implement","uygulamak / hayata geçirmek","v","Implementation: uygulama"),
    _w("imply","ima etmek / işaret etmek","v","Implication: çıkarım"),
    _w("impose","dayatmak","v","Impose sanctions: yaptırım uygula"),
    _w("involve","dahil etmek / içermek","v","Involvement: katılım"),
    _w("isolate","yalıtmak / izole etmek","v","Isolated area: izole bölge"),
    _w("issue","konu / sorun","n","Key issue: temel konu"),
    _w("justify","haklı çıkarmak","v","Justification: gerekçe"),
    _w("launch","başlatmak / fırlatmak","v","Product launch: ürün lansmanı"),
    _w("limit","sınırlamak / sınır","v","Speed limit: hız limiti"),
    _w("locate","bulmak / konumlandırmak","v","Location: konum"),
    _w("maintain","korumak / sürdürmek","v","Maintain balance: denge koru"),
    _w("major","büyük / önemli / ana dal","adj","Major problem: büyük sorun"),
    _w("manage","yönetmek / başarmak","v","Management: yönetim"),
    _w("measure","ölçmek / önlem","v","Measurement: ölçüm"),
    _w("method","yöntem","n","Scientific method: bilimsel yöntem"),
    _w("migrate","göç etmek","v","Migration: göç"),
    _w("minimize","en aza indirmek","v","Minimize risk: riski en aza indir"),
    _w("moderate","ılımlı / orta","adj","Moderate exercise: ılımlı egzersiz"),
    _w("monitor","izlemek / monitör","v","Monitor progress: ilerlemeyi takip et"),
    _w("motivate","motive etmek","v","Motivation: motivasyon"),
    _w("neglect","ihmal etmek","v","Neglect duty: görevi ihmal et"),
    _w("negotiate","müzakere etmek","v","Negotiation: müzakere"),
    _w("obtain","elde etmek / kazanmak","v","Obtain permission: izin al"),
    _w("occur","meydana gelmek","v","Occurrence: olay"),
    _w("participate","katılmak","v","Participation: katılım"),
    _w("perceive","algılamak","v","Perception: algı"),
    _w("perform","gerçekleştirmek / oynamak","v","Performance: performans"),
    _w("permit","izin vermek","v","Permission: izin"),
    _w("preserve","korumak / muhafaza etmek","v","Preservation: koruma"),
    _w("prevent","önlemek / engellemek","v","Prevention: önleme"),
    _w("process","işlemek / süreç","v","Process data: veri işle"),
    _w("produce","üretmek","v","Production: üretim"),
    _w("promote","teşvik etmek / tanıtmak","v","Promotion: terfi / tanıtım"),
    _w("propose","önermek / teklif etmek","v","Proposal: öneri"),
    _w("prove","kanıtlamak","v","Proof: kanıt"),
    _w("provide","sağlamak / sunmak","v","Provider: sağlayıcı"),
    _w("pursue","peşinden gitmek / sürdürmek","v","Pursue a goal: hedefi peşinden git"),
    _w("raise","yükseltmek / yetiştirmek","v","Raise awareness: farkındalık yükselt"),
    _w("recognize","tanımak / fark etmek","v","Recognition: tanıma"),
    _w("reduce","azaltmak / indirmek","v","Reduction: indirim"),
    _w("reflect","yansıtmak / düşünmek","v","Reflection: yansıma"),
    _w("reject","reddetmek","v","Rejection: ret"),
    _w("rely","güvenmek / dayanmak","v","Reliable: güvenilir"),
    _w("replace","değiştirmek / yerine geçmek","v","Replacement: yedek")
],

"🟡 B2 Orta-İleri": [
    _w("abolish","kaldırmak / ilga etmek","v","Abolish slavery: köleliği kaldır"),
    _w("accumulate","biriktirmek / birikmek","v","Accumulate wealth: servet biriktir"),
    _w("allege","iddia etmek","v","Allegedly: iddia edildiğine göre"),
    _w("alleviate","hafifletmek / azaltmak","v","Alleviate pain: acıyı hafiflet"),
    _w("ambiguous","belirsiz / muğlak","adj","Ambi = iki yönlü anlam"),
    _w("amend","değiştirmek / düzeltmek","v","Amendment: değişiklik"),
    _w("anticipate","öngörmek / beklemek","v","Anticipation: beklenti"),
    _w("arbitrary","keyfi / gelişigüzel","adj","Arbitrary decision: keyfi karar"),
    _w("articulate","açık ifade etmek","v","Articulate speaker: açık konuşan"),
    _w("assert","öne sürmek / iddia etmek","v","Assertion: iddia"),
    _w("autonomy","özerklik / otonomi","n","Autonomous vehicle: otonom araç"),
    _w("catastrophe","felaket / yıkım","n","Catastrophic failure: yıkıcı başarısızlık"),
    _w("chronic","kronik / süregelen","adj","Chronic pain: kronik ağrı"),
    _w("cite","alıntı yapmak / belirtmek","v","Cite sources: kaynak göster"),
    _w("coherent","tutarlı / mantıklı","adj","Coherent argument: tutarlı argüman"),
    _w("coincide","çakışmak / aynı anda olmak","v","Coincidence: tesadüf"),
    _w("collapse","çökmek / çöküş","v","Economic collapse: ekonomik çöküş"),
    _w("compensate","telafi etmek","v","Compensation: tazminat"),
    _w("compile","derlemek / toplamak","v","Compilation album: derleme albüm"),
    _w("comprehensive","kapsamlı","adj","Comprehensive study: kapsamlı çalışma"),
    _w("conceal","gizlemek / saklamak","v","Conceal identity: kimliği gizle"),
    _w("contemplate","düşünmek / derin düşünce","v","Contemplation: derin düşünce"),
    _w("contradict","çelişmek / çürütmek","v","Contradiction: çelişki"),
    _w("controversial","tartışmalı","adj","Controversial topic: tartışmalı konu"),
    _w("correlate","ilişkilendirmek","v","Correlation: korelasyon"),
    _w("criterion","kriter / ölçüt","n","Criteria: kriterler (çoğul)"),
    _w("cynical","alaycı / şüpheci","adj","Cynical view: şüpheci bakış"),
    _w("deduce","çıkarmak / sonuç çıkarmak","v","Deduction: tümden gelim"),
    _w("deficiency","eksiklik / yetersizlik","n","Vitamin deficiency: vitamin eksikliği"),
    _w("deliberate","kasıtlı / düşünmek","adj","Deliberately: kasıtlı olarak"),
    _w("derive","türetmek / elde etmek","v","Derived from Latin: Latince'den türemiş"),
    _w("designate","belirlemek / atamak","v","Designated driver: belirlenmiş sürücü"),
    _w("deteriorate","kötüleşmek / bozulmak","v","Deterioration: kötüleşme"),
    _w("devise","tasarlamak / planlamak","v","Devise a strategy: strateji geliştir"),
    _w("dilemma","ikilem","n","Ethical dilemma: etik ikilem"),
    _w("diminish","azalmak / küçülmek","v","Diminishing returns: azalan verimler"),
    _w("disparity","eşitsizlik / uçurum","n","Income disparity: gelir uçurumu"),
    _w("disrupt","bozmak / sekteye uğratmak","v","Disruptive technology: yıkıcı teknoloji"),
    _w("diverse","çeşitli / farklı","adj","Diverse culture: çeşitli kültür"),
    _w("dominant","baskın / egemen","adj","Dominant species: baskın tür"),
    _w("elaborate","ayrıntılı / detaylandırmak","adj","Elaborate plan: ayrıntılı plan"),
    _w("eloquent","belagatli / etkileyici konuşan","adj","Eloquent speech: etkileyici konuşma"),
    _w("empirical","deneysel / ampirik","adj","Empirical evidence: deneysel kanıt"),
    _w("enforce","uygulamak / zorlamak","v","Enforce the law: yasayı uygula"),
    _w("enhance","artırmak / güçlendirmek","v","Enhance performance: performansı artır"),
    _w("enormous","dev / muazzam","adj","Enormous difference: muazzam fark"),
    _w("ethical","etik / ahlaki","adj","Ethical conduct: etik davranış"),
    _w("evident","açık / bariz","adj","Evidently: açıkça"),
    _w("exaggerate","abartmak","v","Stop exaggerating: abartmayı bırak"),
    _w("explicit","açık / net / sarih","adj","Explicit instructions: net talimatlar"),
    _w("exploit","sömürmek / faydalanmak","v","Exploitation: sömürü"),
    _w("fluctuate","dalgalanmak","v","Fluctuating prices: dalgalanan fiyatlar"),
    _w("formulate","formüle etmek","v","Formulate a plan: plan oluştur"),
    _w("foster","teşvik etmek / beslemek","v","Foster creativity: yaratıcılığı teşvik et"),
    _w("fundamental","temel / esaslı","adj","Fundamental rights: temel haklar"),
    _w("hinder","engellemek","v","Hinder progress: ilerlemeyi engelle"),
    _w("hypothesis","hipotez / varsayım","n","Test the hypothesis: hipotezi test et"),
    _w("identical","özdeş / tamamen aynı","adj","Identical twins: özdeş ikizler"),
    _w("ideology","ideoloji","n","Political ideology: siyasi ideoloji"),
    _w("illuminate","aydınlatmak / açıklamak","v","Illuminate the path: yolu aydınlat"),
    _w("immense","muazzam / devasa","adj","Immense pressure: büyük baskı"),
    _w("impartial","tarafsız","adj","Impartial judge: tarafsız hakim"),
    _w("inevitable","kaçınılmaz","adj","Inevitable result: kaçınılmaz sonuç"),
    _w("infer","çıkarsama yapmak","v","Inference: çıkarım"),
    _w("inherent","doğasında olan / özünde","adj","Inherent risk: doğasında olan risk"),
    _w("innovative","yenilikçi","adj","Innovative approach: yenilikçi yaklaşım"),
    _w("insight","kavrayış / içgörü","n","Gain insight: içgörü kazan"),
    _w("integrate","entegre etmek / bütünleştirmek","v","Integration: entegrasyon"),
    _w("integrity","dürüstlük / bütünlük","n","Academic integrity: akademik dürüstlük"),
    _w("intensive","yoğun","adj","Intensive training: yoğun antrenman"),
    _w("interpret","yorumlamak / tercüme etmek","v","Interpretation: yorum"),
    _w("intervene","müdahale etmek","v","Intervention: müdahale"),
    _w("intrinsic","özünde olan / içsel","adj","Intrinsic motivation: içsel motivasyon"),
    _w("investigate","araştırmak / soruşturmak","v","Investigation: soruşturma"),
    _w("irony","ironi / alaycılık","n","Dramatic irony: dramatik ironi"),
    _w("legitimate","meşru / yasal","adj","Legitimate claim: meşru talep"),
    _w("liable","sorumlu / yükümlü","adj","Liable for damages: zarar için sorumlu"),
    _w("logical","mantıklı","adj","Logical conclusion: mantıklı sonuç"),
    _w("manipulation","manipülasyon / hile","n","Emotional manipulation: duygusal manipülasyon"),
    _w("marginal","marjinal / kenar","adj","Marginal gain: küçük kazanım"),
    _w("massive","devasa / büyük","adj","Massive improvement: devasa gelişme"),
    _w("mechanism","mekanizma","n","Defence mechanism: savunma mekanizması"),
    _w("mediocre","vasat / sıradan","adj","Mediocre performance: vasat performans"),
    _w("migration","göç","n","Mass migration: kitlesel göç"),
    _w("mutual","karşılıklı / ortak","adj","Mutual benefit: karşılıklı fayda"),
    _w("narrative","anlatı / öykü","n","Dominant narrative: hâkim anlatı"),
    _w("negligible","ihmal edilebilir / önemsiz","adj","Negligible effect: önemsiz etki"),
    _w("neutral","tarafsız / nötr","adj","Neutral stance: tarafsız tutum"),
    _w("notion","kavram / fikir","n","Common notion: yaygın kavram"),
    _w("objective","nesnel / amaç","adj","Objective analysis: nesnel analiz"),
    _w("obsolete","eski / kullanımdan çıkmış","adj","Obsolete technology: eski teknoloji"),
    _w("ongoing","devam eden / süregelen","adj","Ongoing conflict: devam eden çatışma"),
    _w("oppose","karşı çıkmak","v","Opposition: muhalefet"),
    _w("optimistic","iyimser","adj","Optimistic outlook: iyimser bakış"),
    _w("outcome","sonuç / çıktı","n","Positive outcome: olumlu sonuç"),
    _w("overcome","üstesinden gelmek","v","Overcome obstacles: engelleri aş"),
    _w("perceive","algılamak","v","Perception: algı"),
    _w("persist","ısrar etmek / devam etmek","v","Persistent rain: sürekli yağmur"),
    _w("phenomenon","fenomen / olgu","n","Natural phenomenon: doğal fenomen"),
    _w("pioneer","öncü / çığır açan","n","Pioneer in science: bilim öncüsü"),
    _w("plausible","makul / mantıklı","adj","Plausible explanation: makul açıklama"),
    _w("portray","tasvir etmek / betimlemek","v","Portrait: portre"),
    _w("pragmatic","pragmatik / pratik","adj","Pragmatic approach: pratik yaklaşım"),
    _w("precedent","emsal / önceki örnek","n","Set a precedent: emsal oluştur"),
    _w("predict","öngörmek / tahmin etmek","v","Prediction: tahmin"),
    _w("prejudice","önyargı","n","Racial prejudice: ırksal önyargı"),
    _w("prominent","öne çıkan / seçkin","adj","Prominent figure: öne çıkan şahsiyet"),
    _w("proportion","oran / orantı","n","In proportion: orantılı olarak"),
    _w("radical","köklü / radikal","adj","Radical change: köklü değişim"),
    _w("reinforce","güçlendirmek / pekiştirmek","v","Reinforce learning: öğrenmeyi pekiştir"),
    _w("relevant","ilgili / alakalı","adj","Relevant information: ilgili bilgi"),
    _w("reluctant","isteksiz / gönülsüz","adj","Reluctant to change: değişime isteksiz"),
    _w("resolve","çözmek / kararlılık","v","Resolve conflict: çatışmayı çöz"),
    _w("retain","korumak / tutmak","v","Retain information: bilgiyi akılda tut"),
    _w("reveal","ortaya koymak / ifşa etmek","v","Revelation: ifşa"),
    _w("rigorous","titiz / sıkı","adj","Rigorous testing: titiz test"),
    _w("scrutiny","titiz inceleme","n","Under scrutiny: inceleme altında"),
    _w("straightforward","doğrudan / kolay","adj","Straightforward answer: doğrudan cevap"),
    _w("subsequent","sonraki / ardından gelen","adj","Subsequent events: sonraki olaylar"),
    _w("substantial","önemli / büyük","adj","Substantial evidence: önemli kanıt"),
    _w("subtle","ince / belirgin olmayan","adj","Subtle difference: ince fark"),
    _w("sufficient","yeterli","adj","Sufficient time: yeterli zaman"),
    _w("suppress","bastırmak / engellemek","v","Suppress emotions: duyguları bastır"),
    _w("sustain","sürdürmek / beslemek","v","Sustainable development: sürdürülebilir kalkınma"),
    _w("tackle","ele almak / üstesinden gelmek","v","Tackle a problem: sorunu ele al"),
    _w("tendency","eğilim / yönelim","n","Tendency to procrastinate: erteleme eğilimi"),
    _w("theoretical","teorik / kuramsal","adj","Theoretical framework: teorik çerçeve"),
    _w("undermine","zayıflatmak / baltalamak","v","Undermine authority: otoriteyi baltal"),
    _w("universal","evrensel","adj","Universal truth: evrensel gerçek"),
    _w("valid","geçerli / haklı","adj","Valid argument: geçerli argüman"),
    _w("verify","doğrulamak","v","Verify the facts: gerçekleri doğrula"),
    _w("widespread","yaygın","adj","Widespread belief: yaygın inanç")
],

"🔴 C1 İleri": [
    _w("abdicate","tahttan çekilmek / vazgeçmek","v","Abdicate responsibility: sorumluluktan kaçmak"),
    _w("aberration","sapma / anormallik","n","Statistical aberration: istatistiksel sapma"),
    _w("abstain","çekimser kalmak / kaçınmak","v","Abstain from voting: oylamada çekimser"),
    _w("accentuate","vurgulamak / belirginleştirmek","v","Accentuate the positive: olumluyu vurgula"),
    _w("acrimony","sertlik / husumet","n","Acrimonious debate: sert tartışma"),
    _w("advocate","savunmak / savunucu","v","Advocate for rights: haklara savunuculuk"),
    _w("aesthetic","estetik","adj","Aesthetic appeal: estetik çekicilik"),
    _w("aggravate","kötüleştirmek / sinirlendirmek","v","Aggravate the situation: durumu kötüleştir"),
    _w("allegiance","bağlılık / sadakat","n","Pledge allegiance: sadakat yemini"),
    _w("allude","ima etmek / değinmek","v","Allusion: ima / gönderme"),
    _w("ambivalent","kararsız / çelişkili","adj","Ambivalent feelings: çelişkili duygular"),
    _w("anomaly","anomali / aykırılık","n","Statistical anomaly: istatistiksel aykırılık"),
    _w("antagonist","karşıt / muhalif","n","Antagonistic behaviour: düşmanca davranış"),
    _w("apprehensive","endişeli / kaygılı","adj","Apprehensive about change: değişimden endişeli"),
    _w("aptitude","yatkınlık / doğal yetenek","n","Aptitude test: yetenek testi"),
    _w("archaic","arkaik / çok eski","adj","Archaic language: eski dil"),
    _w("arduous","meşakkatli / yorucu","adj","Arduous task: yorucu görev"),
    _w("aspire","özlemek / arzulamak","v","Aspiration: özlem / hırs"),
    _w("astute","kurnaz / zeki / anlayışlı","adj","Astute observer: anlayışlı gözlemci"),
    _w("atrocity","vahşet / zulüm","n","War atrocity: savaş vahşeti"),
    _w("audacious","cesur / cüretkâr","adj","Audacious plan: cesur plan"),
    _w("austerity","kemer sıkma / tasarruf","n","Austerity measures: tasarruf önlemleri"),
    _w("authoritative","yetkili / güvenilir","adj","Authoritative source: güvenilir kaynak"),
    _w("aversion","tiksinti / isteksizlik","n","Aversion to risk: riskten kaçınma"),
    _w("blatant","apaçık / utanmaz","adj","Blatant lie: apaçık yalan"),
    _w("brevity","kısalık / özlülük","n","Brevity is the soul of wit"),
    _w("candid","açık sözlü / samimi","adj","Candid opinion: dürüst görüş"),
    _w("capricious","kaprisli / değişken","adj","Capricious weather: değişken hava"),
    _w("catalyst","katalizör / tetikleyici","n","Catalyst for change: değişimin tetikleyicisi"),
    _w("causality","nedensellik","n","Causality vs correlation: nedensellik vs korelasyon"),
    _w("circumvent","atlatmak / önüne geçmek","v","Circumvent the law: yasayı atlatmak"),
    _w("clandestine","gizli / el altından","adj","Clandestine operation: gizli operasyon"),
    _w("coerce","zorlamak / baskı yapmak","v","Coercion: zorlama"),
    _w("cognition","biliş / zihinsel süreç","n","Cognitive science: biliş bilimi"),
    _w("complacent","kendinden memnun / kayıtsız","adj","Don't be complacent: rehavete kapılma"),
    _w("concise","kısa ve öz","adj","Concise answer: kısa ve öz cevap"),
    _w("condescending","küçümseyici / tepeden bakan","adj","Condescending tone: küçümseyici ton"),
    _w("conjecture","tahmin / spekülasyon","n","Mere conjecture: sadece tahmin"),
    _w("connotation","çağrışım / yan anlam","n","Negative connotation: olumsuz çağrışım"),
    _w("consensus","uzlaşı / fikir birliği","n","Reach consensus: uzlaşıya var"),
    _w("conspicuous","göze çarpan / dikkat çekici","adj","Conspicuous consumption: gösterişçi tüketim"),
    _w("contempt","hor görme / aşağılama","n","Contempt of court: mahkemeye saygısızlık"),
    _w("contend","mücadele etmek / iddia etmek","v","Contender: yarışmacı"),
    _w("convoluted","karmaşık / girift","adj","Convoluted argument: girift tartışma"),
    _w("corroborate","doğrulamak / desteklemek","v","Corroborating evidence: destekleyici kanıt"),
    _w("covert","gizli / örtülü","adj","Covert operation: gizli operasyon"),
    _w("credibility","güvenilirlik / inanılırlık","n","Credibility crisis: güven krizi"),
    _w("cursory","yüzeysel / aceleyle yapılmış","adj","Cursory glance: şöyle bir bakış"),
    _w("cynicism","sinizm / kuşkuculuk","n","Healthy cynicism: sağlıklı kuşkuculuk"),
    _w("deceptive","yanıltıcı / aldatıcı","adj","Deceptive appearance: aldatıcı görünüm"),
    _w("defunct","artık var olmayan / çökmüş","adj","Defunct company: artık olmayan şirket"),
    _w("denounce","kınamak / ihbar etmek","v","Denounce corruption: yolsuzluğu kına"),
    _w("depict","tasvir etmek / resmini çizmek","v","Depicted in the novel: romanda tasvir edilen"),
    _w("derogatory","aşağılayıcı / küçültücü","adj","Derogatory remarks: aşağılayıcı yorumlar"),
    _w("deter","caydırmak","v","Deterrence: caydırıcılık"),
    _w("dichotomy","ikilik / karşıtlık","n","False dichotomy: yanlış ikilik"),
    _w("diffuse","yaymak / dağılmış","v","Diffuse tension: gerilimi dağıt"),
    _w("diligent","gayretli / çalışkan","adj","Diligent student: çalışkan öğrenci"),
    _w("discern","fark etmek / seçmek","v","Discerning eye: seçici göz"),
    _w("discrepancy","tutarsızlık / çelişki","n","Discrepancy in data: verideki çelişki"),
    _w("disdain","küçümseme / aşağılama","n","Disdainful look: küçümseyici bakış"),
    _w("dissent","karşı çıkmak / muhalefet","v","Dissenting opinion: karşı görüş"),
    _w("dogmatic","dogmatik / bağnaz","adj","Dogmatic belief: katı inanç"),
    _w("dubious","şüpheli / kuşkulu","adj","Dubious claim: şüpheli iddia"),
    _w("eccentric","tuhaf / alışılmışın dışında","adj","Eccentric behaviour: tuhaf davranış"),
    _w("elusive","ele geçmez / zor bulunan","adj","Elusive truth: ele geçmez gerçek"),
    _w("embody","somutlaştırmak / temsil etmek","v","Embody an idea: fikri somutlaştır"),
    _w("enigmatic","gizemli / muammalı","adj","Enigmatic smile: gizemli gülümseme"),
    _w("entail","gerektirmek / kapsamak","v","Entail consequences: sonuçları kapsamak"),
    _w("ephemeral","geçici / kısa ömürlü","adj","Ephemeral trend: kısa ömürlü eğilim"),
    _w("equivocal","belirsiz / çift anlamlı","adj","Equivocal answer: muğlak cevap"),
    _w("eradicate","kökünü kazımak","v","Eradicate poverty: yoksulluğu yok et"),
    _w("erroneous","hatalı / yanlış","adj","Erroneous assumption: hatalı varsayım"),
    _w("esoteric","ezoterik / anlaşılması güç","adj","Esoteric knowledge: gizli bilgi"),
    _w("exacerbate","kötüleştirmek / şiddetlendirmek","v","Exacerbate the problem: sorunu kötüleştir"),
    _w("exemplify","örneklemek / örnek oluşturmak","v","Exemplify excellence: mükemmelliği örnekle"),
    _w("extraneous","alakasız / dışarıdan gelen","adj","Extraneous information: alakasız bilgi"),
    _w("fallacy","yanılgı / safsata","n","Logical fallacy: mantık yanılgısı"),
    _w("fervent","ateşli / coşkulu","adj","Fervent supporter: ateşli destekçi"),
    _w("fortuitous","tesadüfi / şans eseri","adj","Fortuitous meeting: tesadüfi buluşma"),
    _w("frugal","tutumlu / idaeli","adj","Frugal lifestyle: tutumlu yaşam"),
    _w("futile","boşuna / nafile","adj","Futile attempt: nafile deneme"),
    _w("gregarious","sosyal / insancıl","adj","Gregarious personality: sosyal kişilik"),
    _w("hamper","engellemek / zorlaştırmak","v","Hamper progress: ilerlemeyi engelle"),
    _w("harbinger","haberci / öncü işaret","n","Harbinger of doom: felaket habercisi"),
    _w("hubris","kibir / aşırı özgüven","n","Hubris leads to downfall: kibir çöküşe götürür"),
    _w("hypocritical","ikiyüzlü","adj","Hypocritical behaviour: ikiyüzlü davranış"),
    _w("idiosyncratic","kendine özgü / tuhaf","adj","Idiosyncratic style: kendine özgü üslup"),
    _w("immutable","değiştirilemez / kalıcı","adj","Immutable law: değişmez yasa"),
    _w("imperative","zorunlu / emir","adj","It is imperative: zorunludur"),
    _w("incisive","keskin / zekice","adj","Incisive analysis: keskin analiz"),
    _w("incongruous","uyumsuz / yersiz","adj","Incongruous remark: yersiz yorum"),
    _w("indignant","öfkeli / kızgın","adj","Indignant response: öfkeli yanıt"),
    _w("inexorable","durdurulamaz / amansız","adj","Inexorable decline: durdurulamaz düşüş"),
    _w("ingenious","yaratıcı / zekice","adj","Ingenious solution: zekice çözüm"),
    _w("innate","doğuştan / içgüdüsel","adj","Innate ability: doğuştan gelen yetenek"),
    _w("insidious","sinsi / fark edilmez biçimde zararlı","adj","Insidious disease: sinsi hastalık"),
    _w("intangible","soyut / elle tutulamaz","adj","Intangible assets: maddi olmayan varlıklar"),
    _w("meticulous","titiz / çok dikkatli","adj","Meticulous attention: titiz dikkat"),
    _w("mitigate","hafifletmek / azaltmak","v","Mitigate risk: riski azalt"),
    _w("mundane","sıradan / gündelik","adj","Mundane tasks: sıradan görevler"),
    _w("nuance","nüans / ince fark","n","Nuanced argument: nüanslı tartışma"),
    _w("omnipotent","her şeye gücü yeten","adj","Omnipotent ruler: mutlak güçlü lider"),
    _w("ostensible","görünürde / zahiri","adj","Ostensible reason: görünürdeki neden"),
    _w("paradigm","paradigma / örüntü","n","Paradigm shift: paradigma değişimi"),
    _w("paradox","paradoks / çelişki","n","Logical paradox: mantıksal paradoks"),
    _w("partisan","taraftar / partizan","adj","Partisan politics: partizan siyaset"),
    _w("pejorative","küçültücü / aşağılayıcı","adj","Pejorative term: küçültücü terim"),
    _w("perpetuate","sürdürmek / devam ettirmek","v","Perpetuate a myth: efsaneyi sürdür"),
    _w("pervasive","yaygın / her yere sızan","adj","Pervasive influence: yaygın etki"),
    _w("polarise","kutuplaştırmak","v","Polarising debate: kutuplaştırıcı tartışma"),
    _w("pragmatism","pragmatizm / pratikçilik","n","Political pragmatism: siyasi pragmatizm"),
    _w("precarious","istikrarsız / tehlikeli","adj","Precarious position: tehlikeli konum"),
    _w("proliferate","çoğalmak / yayılmak","v","Nuclear proliferation: nükleer yayılma"),
    _w("propensity","eğilim / yatkınlık","n","Propensity for risk: risk eğilimi"),
    _w("reconcile","uzlaştırmak / barıştırmak","v","Reconcile differences: farklılıkları uzlaştır"),
    _w("rhetoric","retorik / söylem","n","Political rhetoric: siyasi söylem"),
    _w("rudimentary","temel / ilkel","adj","Rudimentary skills: temel beceriler"),
    _w("skeptical","şüpheci / kuşkulu","adj","Skeptical of claims: iddialara şüpheci"),
    _w("solitary","yalnız / tek başına","adj","Solitary confinement: tecrit"),
    _w("stagnant","durgun / gelişmeyen","adj","Stagnant economy: durgun ekonomi"),
    _w("stringent","sıkı / katı","adj","Stringent regulations: sıkı kurallar"),
    _w("subjective","öznel","adj","Subjective opinion: öznel görüş"),
    _w("superficial","yüzeysel","adj","Superficial analysis: yüzeysel analiz"),
    _w("surpass","geçmek / aşmak","v","Surpass expectations: beklentileri aş"),
    _w("susceptible","duyarlı / yatkın","adj","Susceptible to disease: hastalığa yatkın"),
    _w("tenuous","zayıf / ince","adj","Tenuous connection: zayıf bağlantı"),
    _w("trivial","önemsiz / basit","adj","Trivial matter: önemsiz konu"),
    _w("unequivocal","kesin / net / açık","adj","Unequivocal support: kesin destek"),
    _w("unprecedented","emsalsiz / benzeri görülmemiş","adj","Unprecedented growth: benzeri görülmemiş büyüme"),
    _w("verbose","fazla konuşkan / sözcük yükü","adj","Verbose writing: kelime dolduran yazı"),
    _w("vindicate","haklı çıkarmak","v","Vindicated by evidence: kanıtla haklı çıkmak"),
    _w("volatile","uçucu / değişken / patlamaya hazır","adj","Volatile market: değişken piyasa")
]

}; // YDT_STARTER_PACK sonu

// DEFAULT_VOCAB olarak Starter Pack kullanılır
const DEFAULT_VOCAB = YDT_STARTER_PACK;

function loadUserScopedData() {
    const uid = window._currentUser?.uid || 'guest';

    const rawAD = localStorage.getItem(`ydt_${uid}_all_data`);
    const rawST = localStorage.getItem(`ydt_${uid}_stats`);

    let userData = null;
    if (rawAD) { try { userData = JSON.parse(rawAD); } catch(e) {} }

    if (userData && Object.keys(userData).length > 0) {
        // Kullanıcı verisi var — Starter Pack listeleri yoksa ekle
        const merged = { ...DEFAULT_VOCAB };
        Object.keys(userData).forEach(k => { merged[k] = userData[k]; });
        allData = merged;
    } else {
        // Yeni kullanıcı / guest — eski veriyi kontrol et
        const legacyRaw = localStorage.getItem('ydt_all_data');
        let legacyData  = null;
        if (legacyRaw) { try { legacyData = JSON.parse(legacyRaw); } catch(e) {} }
        allData = legacyData && Object.keys(legacyData).length > 0
            ? { ...DEFAULT_VOCAB, ...legacyData }
            : { ...DEFAULT_VOCAB };
    }

    // Stats
    let parsedStats = null;
    if (rawST) { try { parsedStats = JSON.parse(rawST); } catch(e) {} }
    if (!parsedStats) {
        const legacyST = localStorage.getItem('ydt_stats');
        if (legacyST) { try { parsedStats = JSON.parse(legacyST); } catch(e) {} }
    }
    stats = parsedStats || { totalAnswers: 0, correctAnswers: 0, totalMinutes: 0 };
    if (isNaN(stats.totalMinutes)) stats.totalMinutes = 0;
}

// İlk yükleme — auth henüz hazır değil → guest olarak başlar
loadUserScopedData();

function _saveData() {
    const uid = window._currentUser?.uid || 'guest';
    localStorage.setItem(`ydt_${uid}_all_data`, JSON.stringify(allData));
    localStorage.setItem(`ydt_${uid}_stats`,    JSON.stringify(stats));
}
